### ISSUE TITLE
Unsupported Python / Resolve version

### ISSUE THREAD

**Issue by Reelback96** [octimot/StoryToolkitAI#1]
I'm not a programmer, however, I have installed this successfully. When I run it, I receive the error:

`SyntaxError: invalid syntax`
`Computer1:StoryToolkitAI-main computer1$ python app.py`
`Traceback (most recent call last):`
`  File "app.py", line 14, in <module>`
`    import mots_resolve`
`  File "/Users/libraryfilmso4/Downloads/StoryToolkitAI-main/mots_resolve.py", line 176`
`    marker_data = {**empty_marker_data, **marker_data}
                    ^
`

I'd love to test this out, so any help would be awesome.

**Comment by octimot** [comment]
That's unusual. What python version are you using?
`python --version`

**Comment by Reelback96** [comment]
I'm running Python 2.7.16

When I attempted to run on Python 3.10.7 I received this error:

```
Librarys-iMac-2:StoryToolkitAI-main libraryfilmso4$ python3 app.py
Starting GUI
Unable to find module DaVinciResolveScript from $PYTHONPATH - trying default locations
Fusion: Unsupported Python version
Segmentation fault: 11
```

**Comment by Reelback96** [comment]
I've additionally successfully installed (in reverse order)

six-1.16.0
whisper-1.1.10
timecode-1.3.1 (sourced from here: https://pypi.org/project/timecode/)

torch
torchvision
torchaudio 
numpy
future 
six (1.4.1)
pillow>=4.1.1

I got these from the requirements check document

**Comment by octimot** [comment]
Unfortunately Python 2.7 is too old for most of the code. We use the tool on 3.9.13 and Whisper requires at least 3.9.9.

Which version of Resolve and/or Fusion do you have installed?

**Comment by octimot** [comment]
whisper-1.1.10 is a different library I believe.

You need to get the right whisper via git using the command in the README file. Again, this only works on python 3.9.9 and later

**Comment by octimot** [comment]
I recommend this how-to for installing multiple versions of python on MacOS: https://jordanthomasg.medium.com/python-development-on-macos-with-pyenv-2509c694a808

Although 3.10 should also work fine for now, the error you get there is weird - it could be that the Resolve library you're using doesn't support that version.

Are you running Resolve 18?

**Comment by Reelback96** [comment]
Thanks for all this info! I will install the correct whisper via GitHub.

We're on Resolve 17.4.5

**Comment by Reelback96** [comment]
Alright, so I installed the correct whisper with: 

`Computer1:StoryToolkitAI-main computer1$ pip3 install git+https://github.com/openai/whisper.git`

Then ran the app the received this error:

```
Computer1:StoryToolkitAI-main computer1$ python3 app.py
Traceback (most recent call last):
  File "/Users/computer1/Downloads/StoryToolkitAI-main/app.py", line 16, in <module>
    import whisper
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/whisper/__init__.py", line 8, in <module>
    import torch
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/__init__.py", line 202, in <module>
    from torch._C import *  # noqa: F403
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/_C.cpython-310-darwin.so, 2): Library not loaded: @loader_path/../.dylibs/libomp.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
  Reason: no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/lib/../.dylibs/libomp.dylib: cannot load 'libomp.dylib' (load command 0x80000034 is unknown)
	/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/lib/../.dylibs/libomp.dylib: cannot load 'libomp.dylib' (load command 0x80000034 is unknown)
```

**Comment by octimot** [comment]
Looks good so far! 

OS X 10.14 shouldn't be a problem, but be careful when you update as it may mess up with your python installation - easy fix, but just be aware of it.

We had a previous version of the tool working on Resolve 17, but we updated to 18 and  now it's hard to test.

Stupid question: is Resolve open? If yes, can you also open a project?

Also, do you see the GUI on the screen? The transcription/translation should work without Resolve.

**Comment by Reelback96** [comment]
Thanks for the tip about 10.14!

Resolve is open, as is a project. I am seeing a window for the GUI, but it's a blank white screen. I was able to click on the buttons by referencing the GUI png, and while it didn't recognize resolve I was able to select a standalone WAV file. I didn't let it run yet.

**Comment by octimot** [comment]
After more tests it seems that unfortunately I can't make it work stable enough on Resolve versions earlier than 18. Resolve 17 and earlier APIs ony support Python up to 3.6, but Whisper and its dependencies need something more recent like Python 3.9.

The GUI issue shouldn't happen though. Did you get the last app update that I pushed a few hours ago? What happens if you don't start Resolve?

Also, I suggest using a shorter audio file to see if the transcription works. On a non-CUDA machine the transcription could take longer 1.5x or more than the length of the audio file itself - depending on your CPU.

**Comment by Reelback96** [comment]
I've updated Resolve to 18 and did a fresh install of all required components. One note I'd make - it doesn't prompt you to install timecode if you don't have it, nor is that listed in the readme. That might just be assumed, but it took a little intuition for me to figure out that I needed to install it.

I've now got a visible GUI, and was able to get an output to work from a Resolve timeline. It's currently analyzing the 3 min clip I ran through it to test. I hit some sort of error involving ffmpeg (which I definitely have installed):

```
LibraryFilmsO26:StoryToolkitAI-main LibraryFilmsO26$ python3 app.py
Running StoryToolkit version 0.16.2
Using device: cpu
Unable to find module DaVinciResolveScript from $PYTHONPATH - trying default locations
Current Project: Untitled Project
Resolve Error. Retrying in a few seconds. (1664935260)
Resolve Communication Error. Is your Resolve project open?
Starting StoryToolkitAI GUI
Prompting user for render path.
Saving into /Volumes/SR CLONE 2/DOWNEY/GG DOWNEY/04_OUTPUT/20221004 and starting render.
100%|█████████████████████████████████████| 1.42G/1.42G [00:49<00:00, 30.9MiB/s]
Processing /Volumes/SR CLONE 2/DOWNEY/GG DOWNEY/04_OUTPUT/20221004/Ramon INTV for AI Translation Test.wav 1664935647.mov.
This will take a while depending on your CPU/GPU. Do not exit the app until it finished or you will have to start all over.
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/whisper/transcribe.py:78: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
Exception in thread Thread-1 (transcribe):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/LibraryFilmsO26/Documents/AI GAMES/StoryToolkitAI-main/app.py", line 200, in transcribe
    result = model.transcribe(audio_path)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/whisper/transcribe.py", line 84, in transcribe
    mel = log_mel_spectrogram(audio)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/whisper/audio.py", line 111, in log_mel_spectrogram
    audio = load_audio(audio)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/whisper/audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ffmpeg/_run.py", line 313, in run
    process = run_async(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ffmpeg/_run.py", line 284, in run_async
    return subprocess.Popen(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```

**Comment by octimot** [comment]
> I've updated Resolve to 18 and did a fresh install of all required components. One note I'd make - it doesn't prompt you to install timecode if you don't have it, nor is that listed in the readme. That might just be assumed, but it took a little intuition for me to figure out that I needed to install it.

Did you run `pip install -r requirements.txt`? Timecode is in the requirements file and this is usually the standard process to have all the dependencies working. But you're right, this might not be obvious for everyone - I'll update the Readme with more detailed installation steps.

> I hit some sort of error involving ffmpeg (which I definitely have installed)
Running  `pip install -r requirements.txt` should solve this since you need to have ffmpeg python too. If it doesn't solve it (or you already did it), sometimes you need to add ffmpeg manually in your PATH variable.

Let me know if this helps!

**Comment by Reelback96** [comment]
I got it working! Turns out it couldn't find the executable for ffmpeg. Not sure why!

**Comment by octimot** [comment]
Cool! I'm glad it works. Did you manually add the path or how did you fix it?

BTW, maybe sure you give the last update a try.

**Comment by Reelback96** [comment]
I added the ffmpeg executable path to the .bash_profile file:

```
# Setting PATH for Python 3.10
# The original version is saved in .bash_profile.pysave
PATH="/Applications:/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ffmpeg:/Library/Frameworks/Python.framework/Versions/3.10/bin:${PATH}"
PYTHONPATH="/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ffmpeg:/Library/Frameworks/Python.framework/Versions/3.10/bin:${PATH}"
export PATH
export PYTHONPATH
```

I'll be sure to try the latest update! I just have to download it and open the app.py file the same as before, right? Should I need to install any additional components?
