### ISSUE TITLE
Mac M1 standalone installer

### ISSUE THREAD

**Issue by andymees** [octimot/StoryToolkitAI#10]
Just a note to let you know that when I installed StoryToolkitAI v0.16.15 for M1 on my laptop, the install script did not complete successfully until I manually created a 'CommandLineTools' folder in /Library/Developer ... until I did that it would fail on the CommandLineTools install.

Also note that the second instruction brew install ffmpeg would not run until I manually added the necessary PATH variables.

None of it was an issue, but 'install homebrew and ffmpeg with 2 commands" could be untrue/misleading for some users.

**Comment by octimot** [comment]
Thanks for the feedback!! Let me try to unpack it a bit to make this info available to others.

> the install script did not complete successfully

This is weird. By "installer script" you mean the installation of homebrew (step 1)

> the second instruction brew install ffmpeg would not run until I manually added the necessary PATH variables.

This is also weird. Did you use `sudo` in front of the commands when going through step 1 or 2?

> None of it was an issue, but 'install homebrew and ffmpeg with 2 commands" could be untrue/misleading for some users.

That's why the phrase

**Comment by andymees** [comment]
_>This is weird. By "installer script" you mean the installation of homebrew (step 1)_

Yes, thanks... homebrew install.sh failed to create the needed directory, so I created it manually.

_>This is also weird. Did you use sudo in front of the commands when going through step 1 or 2?_

Nope. I copied and pasted the commands per instructions, no sudo.
Step 1 prompted for my password but, for me, failed repeatedly until I manually created the directory.
Step 2 worked fine as is... I just needed to manually add the PATH variables for the 'brew' command first.

_>and it should work_
Yep, no issues with StoryToolkitAI running and working post installation, the issues were only with the preceding homebrew setup... only mentioning in case you want to manage expectations for Step 1 too ;)

**Comment by octimot** [comment]
> Yep, no issues with StoryToolkitAI running and working post installation, the issues were only with the preceding homebrew setup... only mentioning in case you want to manage expectations for Step 1 too ;)

Of course, I agree, this feedback is super important!

> Yes, thanks... homebrew install.sh failed to create the needed directory, so I created it manually.

It seems that you need xcode command line tools installed also as per this troubleshooting guide: https://docs.brew.sh/Common-Issues#brew-complains-about-absence-of-command-line-tools

Nobody else complained about it so far. Maybe some Macs have it already?

Ideally, users should just install ffmpeg, but I'm not sure if that's easier without homebrew for the the average user...
