### ISSUE TITLE
How to deal with the part that no caption generated? Also why each line ended too soon?

### ISSUE THREAD

**Issue by dausruddin** [octimot/StoryToolkitAI#106]
Hi.

Cool tool. I have been dreaming about tool like this for years!

I am trying to transcribe a classic anime episode. I am having 2 issues.

1. There are some part that no caption generated. The speech is there, but subtitle is blank. I have tried re-transcribe with no luck.
    There should be a caption at where the playhead is in image below, but there is none.
![image](https://github.com/octimot/StoryToolkitAI/assets/5763466/33f96efe-841a-4c47-88ec-afc215ca2e3c)
How do I deal with this?
.
.

2. After the subtitle has finished generated, I load it into Davinci timeline. My problem is, why the timing is kind of short? Like the character is still talking, but subtitle already vanished.
    In image below, the line should still be showing until where the playhead is, but it already ended like in the image.
![image](https://github.com/octimot/StoryToolkitAI/assets/5763466/2cc93f39-ba63-4ae3-a124-2cfcb8f4b61a)
This happen throughout the entire video.

**Comment by octimot** [comment]
Hello,

Which version of the tool are you using? Which model are you using to transcribe? 

Is the original audio in Japanese (are you translating?) or is it in English?

Need more info.

Cheers!

**Comment by johnwig** [comment]
> There's a weird bug in Resolve which makes it ignore the changes to your SRT file, if it has the same name...
> The workaround that we found is to manually import the SRT file using a different name.
> 
> In fact, you can check if the SRT file is correct by simply opening it in Notepad.

Alright. I'll them in mind.

> Is this happening with large-v2 and "Increased time precision"?
Yep, happened with both medium and large-v2. "Increased time precision" is always checked.

> Again, please make sure that the SRT import is done as mentioned above to avoid the bug in Resolve.

Can confirm I'm using latest version of the SRT file as I can see the missing part which I transcribed later.

**Comment by octimot** [comment]
I'm going to close this issue since it has more to do with the Whisper package than anything we could fix from this side.

Also, we can't test this much over here since we're not seeing it happening on our footage very often...

BTW, version 0.19.4 uses the new Whisper update, which might have improved this.
