### ISSUE TITLE
Way too confusing to find a download link in your README.md

### ISSUE THREAD

**Issue by JeremyBernier** [octimot/StoryToolkitAI#107]
Way too confusing to find a download link in your README.md / documentation. Unless your goal is to prevent people from actually using your software, the download link should be made more prominent.

**Comment by octimot** [comment]
Thanks for the feedback!

Yes, the goal is indeed to prevent people from using this top secret tool!! :-))

But point taken. Does this make more sense: https://github.com/octimot/StoryToolkitAI/tree/main#download-setup--installation?

Cheers

**Comment by JeremyBernier** [comment]
Much better! Thanks!
