### ISSUE TITLE
high dpi menu font size

### ISSUE THREAD

**Issue by pantau000** [octimot/StoryToolkitAI#109]
Menu items are displayed with a very small font on high dpi displays.

**Comment by octimot** [comment]
Could you please post a screenshot? 

Also, are you using Windows 10 or 11?  What is your screen resolution and what's the value selected on the scaling settings?

**Comment by octimot** [comment]
Thanks!

What resolution did you want to write?

**Comment by pantau000** [comment]
sorry, I forgot to mention my screen resolution:
2560x1440 (laptop screen)

**Comment by octimot** [comment]
Alright, thanks! We'll try to reproduce that here and check why that is happening!

**Comment by octimot** [comment]
Fixed since version 0.19.2
