### ISSUE TITLE
"Transcribe Timeline" don't automatically render and transcribe

### ISSUE THREAD

**Issue by dausruddin** [octimot/StoryToolkitAI#114]
**Describe the bug**
When clicking "Transcribe Timeline", timeline don't automatically render. Even if I hit "Render" manually, nothing happen after that.

**To Reproduce**
1. Run Resolve
2. Run StoryToolkitAI and connect to Resolve API 
3. Press "Transcribe Timeline"

**Expected behavior**
Timline automatically render and audio getting transcribed

**Log file**
[app.log](https://github.com/octimot/StoryToolkitAI/files/11929769/app.log)

**Screenshots**
![image](https://github.com/octimot/StoryToolkitAI/assets/5763466/601305a0-e8b5-4504-9ca5-abd8964a19cc)

**System (please complete the following information):**
 - OS: Windows 11
 - Python versions installed on machine: 3.10.11
 - StoryToolkitAI Version: 0.19.1 (git clone)

**Additional context**
N/A

**Comment by octimot** [comment]
Thanks for pointing this out!

Do you start the tool according to the INSTALLATION.md instructions?

```
py StoryToolkitAI\storytoolkitai
```

Cheers

**Comment by octimot** [comment]
Nevermind! 

Try to `git pull` the latest commit and feel free to re-open this issue if it still doesn't work.

Cheers!
