### ISSUE TITLE
last speech timestamp error

### ISSUE THREAD

**Issue by SlyAquaGuy** [octimot/StoryToolkitAI#115]
**Describe the bug**
StoryToolKit throws an error while transcribing audio when Increased Time Precision is enabled. This issue persists across different Models and with several different settings. It's a fantastic tool otherwise.

**To Reproduce**
1. Click on Transcribe Audio
2. Scroll down to Advanced Transcription Settings
3. Enable Increased Time Precision
4. Fill out details for Transcription post-processing
5. See error

**Expected behavior**
Subtitles to be processed as normal and split to the desired length of characters.

**Log file**
[app.log](https://github.com/octimot/StoryToolkitAI/files/11936377/app.log)

**Screenshots**
If possible, add screenshots to help explain your problem.

**System (please complete the following information):**
 - OS: Windows 11
 - Python versions installed on machine: 3.10.5
 - StoryToolkitAI Version: 0.19.1

**Additional context**
StoryToolkit says it is out of date by one patch but git pull garners no response.

**Comment by octimot** [comment]
Hey there!

I think you might have installed a different version of whisper than the one we recommend - see step 8.  [INSTALLATION.md](https://github.com/octimot/StoryToolkitAI/blob/main/INSTALLATION.md#8-install-openai-whisper)

```
pip install -U git+https://github.com/openai/whisper.git@248b6cb124225dd263bb9bd32d060b6517e067f8
```

If this is the case, did you follow the steps exactly, or did you omit the hash string above? Just so we know if something's wrong on our end.

Cheers!

**Comment by octimot** [comment]
BTW, I'll check the new whisper version and come with a patch... but until then, we have to stick with the older version.

**Comment by SlyAquaGuy** [comment]
Ah yep, downgrading the whisper version worked a treat! I think I initially deleted a character from the hash so it was throwing an error on install and I just gunned for the latest version. 

Thanks for making such an amazing tool! This will save me hours of subtitling.

**Comment by octimot** [comment]
Cool! Thanks for the feedback!
