### ISSUE TITLE
Cannot update with "git pull"

### ISSUE THREAD

**Issue by Europa2010AD** [octimot/StoryToolkitAI#117]
**Describe the bug**
While being in the virtual environment (venv), entering `git pull` returns an error saying "fatal: not a git repository (or any of the parent directories): .git"

**To Reproduce**
1. Activate virtual environment via `source venv/bin/activate`
2. While being inside the virtual environment `(venv)`, enter `git pull`
3. Returns error "fatal: not a git repository (or any of the parent directories): .git"

**System (please complete the following information):**
 - OS: MacOS 13.4.1
 - Python versions installed on machine: 3.10
 - StoryToolkitAI Version: latest non-patreon version

**Comment by octimot** [comment]
From here it seems that you might not be in the right folder when you're doing the pull.

So if this is your installation:

```
YOUR_INSTALLATION_FOLDER
+- StoryToolkitAI
+- venv
```

you need to `git pull` while being in the folder `StoryToolkitAI` preferably after venv was activated.

**Comment by octimot** [comment]
I tried to make this more clear in the Installation Guide: [see this](https://github.com/octimot/StoryToolkitAI/blob/main/INSTALLATION.md#updates-on-the-git-version-of-the-tool)

**Comment by Europa2010AD** [comment]
> I tried to make this more clear in the Installation Guide: [see this](https://github.com/octimot/StoryToolkitAI/blob/main/INSTALLATION.md#updates-on-the-git-version-of-the-tool)

Thanks for the help, @octimot ! I was able to run `git pull` successfully with your new instructions.

Just a comment on the updated Installation Guide, if you don't mind:

Right now, under Mac OS, it says "from your installation folder, run:"
```
source StoryToolkitAI/venv/bin/activate
python StoryToolkitAI/storytoolkitai
```
However, if you were already in your installation folder:
```
YOUR_INSTALLATION_FOLDER
+- StoryToolkitAI
+- venv
```
Then `source StoryToolkitAI/venv/bin/activate` wouldn't have worked -- it would have to be `source venv/bin/activate` instead (in fact, this command was included in the original instructions before the update).

So I think in the updated Installation Guide, it should be written as, "from your installation folder, run:"
```
source venv/bin/activate
python StoryToolkitAI/storytoolkitai
```

**Comment by octimot** [comment]
Good point, thanks!

I just fixed it!
