### ISSUE TITLE
Format not recognized - no matter what file used

### ISSUE THREAD

**Issue by co50** [octimot/StoryToolkitAI#118]
**Describe the bug**
When attempting to use the standalone tool, I get the same error "Format not recognized" for any MP4 file whether generated locally or downloaded from Youtube.

**To Reproduce**
1. Open standalone version (latest non-Patreon)
2. Click on 'Transcribe Audio'
3. Choose any video file 
4. ERROR: Traceback (most recent call last):
  File "librosa\core\audio.py", line 176, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "librosa\core\audio.py", line 209, in __soundfile_load
    context = sf.SoundFile(path)
  File "soundfile.py", line 658, in __init__
  File "soundfile.py", line 1216, in _open
soundfile.LibsndfileError: Error opening "C:/Users/mrgre/Desktop/Test Vids to Delete/Carol O'Donnell didn't _feel_ that she was aprty in the Bonnet Shores lawsuit   HD 720p.mp4": Format not recognised.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 9337, in transcribe_from_queue
  File "app.py", line 9843, in whisper_transcribe
  File "librosa\core\audio.py", line 184, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "decorator.py", line 232, in fun
  File "librosa\util\decorators.py", line 60, in __wrapper
    return func(*args, **kwargs)
  File "librosa\core\audio.py", line 241, in __audioread_load
    reader = audioread.audio_open(path)
  File "audioread\__init__.py", line 132, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError

INFO: Transcription queue empty. Going to sleep.

**Expected behavior**
For it to work.

**Log file**
Please include the app.log file - you can find it by clicking on File -> Configuration Directory

**Screenshots**
If possible, add screenshots to help explain your problem.

**System (please complete the following information):**
 - OS: WIndows 10
 - Python versions installed on machine: 3.10.x
 - StoryToolkitAI Version 0.17.16.2

**Additional context**
This occurs no matter which video file is used. This includes MP4 videos downloaded directly from our Youtube channel.
[app.log](https://github.com/octimot/StoryToolkitAI/files/11995905/app.log)

**Comment by octimot** [comment]
Hello,

The error you're seeing is usually thrown when the codec is unrecognized.

What audio codec are you using?

Cheers

**Comment by co50** [comment]
The most recent source video file I tried was downloaded from YouTube, and uses AAC 44100Hz 2.0 chn [English, Audio 1 (AAC, 44.1 kHz, 2.0 chn, 16 bit)]. But every other video I tried got the same error including a 4k video using AC-3 48000Hz 2.0 chn 256 kbit/s.

**Comment by octimot** [comment]
For version 0.17.16.2 I recommend sticking to the instructions here: https://github.com/octimot/StoryToolkitAI/blob/main/FEATURES.md#resolve-transcription_wav-preset

However if that's too complicated, installing FFMPEG on your machine would most likely give the tool the option to convert internally to the format it needs.
Follow the instructions [at step 4 here](https://github.com/octimot/StoryToolkitAI/blob/main/INSTALLATION.md#4-download-and-install-ffmpeg-via-chocolatey).

BTW, if you're using a youtube ripper to download, I know that some of them do sometimes encode videos with errors which the tool might not be able to solve.

Let me know if this works!
Cheers

**Comment by co50** [comment]
I originally tried the power shell install and that failed. Something about one of the elements being an outdated version. Followed the instructions exactly, twice. No luck. But during those steps I installed ffmpeg so that's already on my machine.

For YouTube, I did not rip it. I downloaded it using the built-in option in YouTube studio.

Was happy to pay for the work you've done and get the latest version once I got this working but so far no luck.

**Comment by octimot** [comment]
> I originally tried the power shell install and that failed. Something about one of the elements being an outdated version. Followed the instructions exactly, twice. No luck. But during those steps I installed ffmpeg so that's already on my machine.

Installing FFMPEG through Choco has the benefit of adding all the necessary environment paths, which StoryToolkit might 
use.

But if ffmpeg works from the command line, you can try to convert one of the files to wav mono (just replace input.mp4 and output.wav with your own files):
```
ffmpeg -i input.mp4 -ac 1 -f wav output.wav
```

If you want to convert the all the mp4 files in the folder, try this:
```
for %i in (*.mp4) do ffmpeg -i "%i" -ac 1 "%~ni.wav"
```

Then try to feed the output wav to the tool.

> For YouTube, I did not rip it. I downloaded it using the built-in option in YouTube studio. I am not using Resolve. I am just attempting to transcribe directly.

I'll try this myself when I have a bit of time and check if there's something specific about AAC codec that Youtube is using and we're not handling it properly...

**Comment by co50** [comment]
I just reinstalled FFMpeg using the powershell instructions and gave it another try. This time all videos work. Thanks for helping me sort it. Will buy the fancy one now. :-)

**Comment by co50** [comment]
Upon installing the Patreon version and running for the first time, I got this:

numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\mrgre\AppData\Local\Programs\StoryToolkitAI\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\mrgre\AppData\Local\Programs\StoryToolkitAI\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
ERROR: Traceback (most recent call last):
  File "storytoolkitai\__main__.py", line 57, in <module>
  File "pkg_resources\__init__.py", line 909, in require
  File "pkg_resources\__init__.py", line 800, in resolve
pkg_resources.ContextualVersionConflict: (decorator 5.1.1 (c:\users\mrgre\appdata\local\programs\storytoolkitai), Requirement.parse('decorator<5.0,>=4.0.2'), {'moviepy'})

WARNING: Some of the packages required to run StoryToolkitAI are missing from your Python environment.

WARNING:
If you are running the standalone version of the app, please report this error to the developers together with the log file found at: [app.log.txt](https://github.com/octimot/StoryToolkitAI/files/12002243/app.log.txt)
INFO: Running post-update tasks for 0.19.4...
INFO: Updated config file C:\Users\mrgre\StoryToolkitAI\config.json with last_update data.
INFO: Config file C:\Users\mrgre\StoryToolkitAI\config.json saved.
INFO: Running StoryToolkitAI version 0.19.4 (standalone)
numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\mrgre\AppData\Local\Programs\StoryToolkitAI\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\mrgre\AppData\Local\Programs\StoryToolkitAI\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
INFO: Starting StoryToolkitAI GUI
ERROR: Traceback (most recent call last):
  File "storytoolkitai\__main__.py", line 57, in <module>
  File "pkg_resources\__init__.py", line 909, in require
  File "pkg_resources\__init__.py", line 800, in resolve
pkg_resources.ContextualVersionConflict: (decorator 5.1.1 (c:\users\mrgre\appdata\local\programs\storytoolkitai), Requirement.parse('decorator<5.0,>=4.0.2'), {'moviepy'})

WARNING: Some of the packages required to run StoryToolkitAI are missing from your Python environment.

WARNING:
If you are running the standalone version of the app, please report this error to the developers together with the log file found at: C:\Users\mrgre\StoryToolkitAI\app.log

usage: StoryToolkitAI.0.19.4.WIN.exe [-h] [--mode {gui,cli}] [--debug] [--noresolve]
                                     [--skip-python-check] [--skip-update-check]
                                     [--output-dir OUTPUT_DIR]
                                     [--resolve-render "KEY1=VALUE1", "KEY2=VALUE2", ..."]
                                     [--resolve-render-job "JOB_ID"]
                                     [--resolve-render-data "JSON_DATA"]
StoryToolkitAI.0.19.4.WIN.exe: error: unrecognized arguments: C:\Users\mrgre\AppData\Local\Programs\StoryToolkitAI\StoryToolkitAI.0.19.4.WIN.exe

**Comment by octimot** [comment]
Moving this to #119
