### ISSUE TITLE
Unable to find module DaVinciResolveScript (Windows)

### ISSUE THREAD

**Issue by 01Bookworm01** [octimot/StoryToolkitAI#12]
This might be related to another issue here but I seem to be getting enough differences that I'm doing this as a new issue.

I am very new to all of this Python and coding stuff so I might have messed something up with the instillation, but it was all followed correctly to my knowledge. This is all on windows 10. I was also running all of the commands in command prompt because when I tried in Python it kept giving me syntax errors. I also made my virtual environment with a different command than what is shown in the installation guide. `py -m venv (environment name)` was the command I used in command prompt. When I tried what was suggested, both in and out of python, this is what I got:

`C:\video editing\Storytoolkit>python3.9 virtualenv -p python3.9 venv
'python3.9' is not recognized as an internal or external command,
operable program or batch file.`

`C:\video editing\Storytoolkit>py
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.`
`>>> python3.9 virtualenv -p python3.9 venv`
`  File "<stdin>", line 1`
`python3.9 virtualenv -p python3.9 venv`
`            ^`
`SyntaxError: invalid syntax`

Not sure if any of the above is actually responsible for the this issue or not but I included it to be safe

For the issue itself, whenever I run the command `python StoryToolkitAI/app.py` in my virtual environment, I get this:

`(transcript) C:\video editing\Storytoolkit>python StoryToolkitAI/app.py`
`INFO: Running StoryToolkitAI version 0.16.16`
`INFO: Using cpu for Torch / Whisper.`
`Unable to find module DaVinciResolveScript from $PYTHONPATH - trying default locations`
`Unable to find module DaVinciResolveScript - please ensure that the module DaVinciResolveScript is discoverable by python`
`For a default DaVinci Resolve installation, the module is expected to be located in: C:\ProgramData\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\Modules\`
`Traceback (most recent call last):`
`  File "C:\video editing\Storytoolkit\StoryToolkitAI\python_get_resolve.py", line 13, in GetResolve
    import DaVinciResolveScript as bmd`
`ModuleNotFoundError: No module named 'DaVinciResolveScript'`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):`
  `File "C:\video editing\Storytoolkit\StoryToolkitAI\python_get_resolve.py", line 27, in GetResolve
    bmd = imp.load_source('DaVinciResolveScript', expectedPath+"DaVinciResolveScript.py")`
`  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\imp.py", line 171, in load_source
    module = _load(spec)`
 ` File "<frozen importlib._bootstrap>", line 711, in _load`
`  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked`
`  File "<frozen importlib._bootstrap_external>", line 850, in exec_module`
`  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed`
`  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\Modules\DaVinciResolveScript.py", line 36, in <module>`
`    raise ImportError("Could not locate module dependencies")`
`ImportError: Could not locate module dependencies`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):`
`  File "C:\video editing\Storytoolkit\StoryToolkitAI\app.py", line 3877, in poll_resolve_data
    resolve_data = mots_resolve.get_resolve_data(silent=True)`
`  File "C:\video editing\Storytoolkit\StoryToolkitAI\mots_resolve.py", line 89, in get_resolve_data
    = initialize_resolve(silent=silent)`
`  File "C:\video editing\Storytoolkit\StoryToolkitAI\mots_resolve.py", line 34, in initialize_resolve
    resolve = GetResolve()`
`  File "C:\video editing\Storytoolkit\StoryToolkitAI\python_get_resolve.py", line 32, in GetResolve
    sys.exit()`
`SystemExit`

`WARNING: Resolve is not reachable.`
`INFO: Starting StoryToolkitAI GUI`

Sorry if this is a lot of info, but I'm not sure what is important and what isn't.

**Comment by 01Bookworm01** [comment]
Have been reinstalling everything from step 4 onwards with the installation guide via command prompt, replacing the virtual environment command there with the one I gave up above. With the `pip install git+https://github.com/openai/whisper.git` line I did notice two strange lines but everything else seems to be fine. The lines were `Using legacy 'setup.py install' for whisper, since package 'wheel' is not installed.` and `Using legacy 'setup.py install' for future, since package 'wheel' is not installed.` It also gave me `WARNING: You are using pip version 22.0.4; however, version 22.3 is available.` at the end. Not sure if this will affect anything.

I can't remember if I did the uninstall/install torch stuff in step 8 last time, but I did it this time after running the `pip install -r StoryToolkitAI/requirements.txt` command. Only thing to note here are the following lines:

`Requirement already satisfied: typing-extensions in c:\video editing\storytoolkit\transcript\lib\site-packages (from torch) (4.3.0)`
`Requirement already satisfied: requests in c:\video editing\storytoolkit\transcript\lib\site-packages (from torchvision) (2.28.1)`
`Requirement already satisfied: numpy in c:\video editing\storytoolkit\transcript\lib\site-packages (from torchvision) (1.23.4)`
`Requirement already satisfied: charset-normalizer<3,>=2 in c:\video editing\storytoolkit\transcript\lib\site-packages (from requests->torchvision) (2.1.1)`
`Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\video editing\storytoolkit\transcript\lib\site-packages (from requests->torchvision) (1.26.12)`
`Requirement already satisfied: certifi>=2017.4.17 in c:\video editing\storytoolkit\transcript\lib\site-packages (from requests->torchvision) (2022.9.24)`
`Requirement already satisfied: idna<4,>=2.5 in c:\video editing\storytoolkit\transcript\lib\site-packages (from requests->torchvision) (3.4)`

Apart from that I am still getting the exact same exceptions as above, with Davinci already open and in the project and timeline I want it to be. Only change is I now get `INFO: Using cuda for Torch / Whisper.` instead of `INFO: Using cpu for Torch / Whisper.`
I honestly have no idea what I am doing wrong. Is there something somewhere that I should be turning on or telling it what to do? I already have the external scripting in Davinci set to local.

**Comment by octimot** [comment]
Hey there!

It seems that something is weirdly messed up with your python / virtual environment.

I'll take a closer look at the errors when I have a bit more time, but first thing that pops in my mind is that you're probably either:

a) not using the right Python version due to some missing environment variables-> possible solution: uninstall everything python from OS and reinstall strictly what you need (see instructions)
or
b) you're not installing requirements inside the virtual environment => possible solution: make sure you activate the environment before issuing the `pip install` commands and everything else

Let me know if this helps!

**Comment by 01Bookworm01** [comment]
Will do. I'll keep a running list of what steps I took here in case it messes up again to help with future trouble shooting, and to help anyone with similar issues if this does work.

1. Deleted virtual environment.
2. Uninstalled python 9 from the installer.
3. Made sure to delete python script and py cache from davinci module
4. emptied recycle bin
5. Reinstalled python 9, making sure that `add python 9 to Path` was ticked.
6. opened command prompt in folder where virtual environment will be by typing cmd into address bar
7. Tried to run `python3.9 -m pip install virtualenv` and `python get-pip.py` both in and out of python. Same results as before.
8. Made virtual environment using `py -m venv (environment name)`
9. Opened virtual environment
10.  Ran `pip install git+https://github.com/openai/whisper.git` . Same legacy lines as before.
11. `Ran pip install -r StoryToolkitAI/requirements.txt` . Nearly all requirements already met
12. Ran `pip uninstall torch` . Asked to remove :   
    `c:\video editing\storytoolkit\transcript\lib\site-packages\caffe2\*`
 `   c:\video editing\storytoolkit\transcript\lib\site-packages\functorch\*`
`    c:\video editing\storytoolkit\transcript\lib\site-packages\torch-1.13.0.dist-info\*`
`    c:\video editing\storytoolkit\transcript\lib\site-packages\torch\*`
`    c:\video editing\storytoolkit\transcript\lib\site-packages\torchgen\*`
  `  c:\video editing\storytoolkit\transcript\scripts\convert-caffe2-to-onnx.exe`
  `  c:\video editing\storytoolkit\transcript\scripts\convert-onnx-to-caffe2.exe`
  `  c:\video editing\storytoolkit\transcript\scripts\torchrun.exe`
Accepted
13. Ran `pip cache purge`
14. Ran `pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` . A few requirements already met, all from torch, torchvison or `requests->torchvision` .
15. Opened davinci and timeline. Is studio version. External scripting is used.
16. Ran `python StoryToolkitAI/app.py` . Didn't work again, but also got slightly  different errors:
`(transcript) C:\video editing\Storytoolkit>python StoryToolkitAI/app.py`
`INFO: Running StoryToolkitAI version 0.16.16`
`INFO: Using cuda for Torch / Whisper.`
`Unable to find module DaVinciResolveScript from $PYTHONPATH - trying default locations`
`Traceback (most recent call last):`
  `File "C:\video editing\Storytoolkit\StoryToolkitAI\python_get_resolve.py", line 13, in GetResolve
    import DaVinciResolveScript as bmd`
`ModuleNotFoundError: No module named 'DaVinciResolveScript'`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):`
`  File "C:\video editing\Storytoolkit\StoryToolkitAI\app.py", line 3877, in poll_resolve_data
    resolve_data = mots_resolve.get_resolve_data(silent=True)`
`  File "C:\video editing\Storytoolkit\StoryToolkitAI\mots_resolve.py", line 89, in get_resolve_data
    = initialize_resolve(silent=silent)`
`  File "C:\video editing\Storytoolkit\StoryToolkitAI\mots_resolve.py", line 34, in initialize_resolve
    resolve = GetResolve()`
 ` File "C:\video editing\Storytoolkit\StoryToolkitAI\python_get_resolve.py", line 27, in GetResolve
    bmd = imp.load_source('DaVinciResolveScript', expectedPath+"DaVinciResolveScript.py")`
`  File "C:\Users\rhyzp\AppData\Local\Programs\Python\Python39\lib\imp.py", line 171, in load_source
    module = _load(spec)`
`  File "<frozen importlib._bootstrap>", line 711, in _load`
`  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked`
`  File "<frozen importlib._bootstrap_external>", line 846, in exec_module`
 ` File "<frozen importlib._bootstrap_external>", line 982, in get_code`
`  File "C:\Users\rhyzp\AppData\Local\Programs\Python\Python39\lib\imp.py", line 157, in get_data
    return super().get_data(path)`
 ` File "<frozen importlib._bootstrap_external>", line 1039, in get_data`
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ProgramData\\Blackmagic Design\\DaVinci Resolve\\Support\\Developer\\Scripting\\Modules\\DaVinciResolveScript.py'`

`WARNING: Resolve is not reachable.`


Any ideas where I went wrong? Should I have deleted the toolkit folder as well?

**Comment by octimot** [comment]
Thanks for the step-by-step log!

Questions:

> 3. Made sure to delete python script and py cache from davinci module
Could you please detail this? If you deleted the python scripts from any Blackmagic / Davinci folders, make sure to have them back in. The tool relies on the fact that those scripts are where they should be.

> 16. Ran python StoryToolkitAI/app.py . Didn't work again, but also got slightly different errors
Does the app start and then exits? Or, do you see the GUI? If so, can you transcribe audio files?

**Comment by 01Bookworm01** [comment]
For clarification with the above, the tool does still open, but without any of the davinci integration. I can still run audio files through it and get transcripts. 
Also, as long as the tools is open, it keeps running thorough the tracebacks. I think that might be because there's nothing in the scripts telling it to stop trying, but that's a very armature guess on my part.

**Comment by octimot** [comment]
> Also, as long as the tools is open, it keeps running thorough the tracebacks. I think that might be because there's nothing in the scripts telling it to stop trying, but that's a very armature guess on my part.

This is intended. It will eventually throttle the Resolve polling to every 30 seconds after a few tries to prevent useless calls, but it will still try it nevertheless.

**Comment by 01Bookworm01** [comment]
> > 3. Made sure to delete python script and py cache from davinci module
> 
> Could you please detail this? If you deleted the python scripts from any Blackmagic / Davinci folders, make sure to have them back in. The tool relies on the fact that those scripts are where they should be.

Okay I might have done a bit of a dumb here. My thought process was that getting the requirements from story tool kit was what put the python script in `C:\ProgramData\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\Modules`. So if I removed it for a clear process, it'll just put a new one there. Turns out that was not the case. I removed the python script (DaVinciResolveScript.py) and deleted it from the recycle bin. 
Any easy way for this moron to get it back? Do I need to delete everything from the environment and the kit and run `git clone https://github.com/octimot/StoryToolkitAI.git` ? If so do I need steps 12-14 from up above again?

**Comment by octimot** [comment]
No need to run the steps again (hopefully). You're almost there!

First, to make sure we're in sync with the logic here: StoryToolkitAI doesn't modify/install/touch the Resolve python scripts at all. You basically have them in their installation folder as a result of installing Davinci Resolve. This applies to all the scripts in `C:\ProgramData\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\Modules`, the ones in `C:\Program Files\Blackmagic Design\DaVinci Resolve\`, or any others if they exist.

The proper way to have everything back in place would be to reinstall Resolve, but give me a minute to drop the missing stuff here from one of our workstations, to try that first!

**Comment by octimot** [comment]
This is the DaVinciResolveScript.py from the `C:\ProgramData\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\Modules` from one of our Windows 10 workstations. Simply unzip it in that folder on your machine.

[DaVinciResolveScript.zip](https://github.com/octimot/StoryToolkitAI/files/9901721/DaVinciResolveScript.zip)

**Comment by octimot** [comment]
> 8. Made virtual environment using py -m venv (environment name)

The complete command for creating the virtual environment on Windows if you have `py launcher` installed (which should install itself with all recent official python installers), should be this: `py -3.9 -m venv [environment name]`

The `-3.9` argument makes sure that you are using the python version that you need. Of course, if you are sure that you don't have other python versions installed on your machine, your command is also fine.

> 9. Opened virtual environment

To activate the virtual environment do `[full path to environment]\Scripts\activate.bat`

**Comment by 01Bookworm01** [comment]
> To activate the virtual environment do `[full path to environment]\Scripts\activate.bat`

Because I've been opening the command prompt in the folder the environment is in already, I haven't needed to do the path. I just run `[environment name]\Scripts\activate` and it tells me that it's now in `[environment name]` C:\video editing\Storytoolkit>python StoryToolkitAI/app.py`.

Also, popped that py script back where it belongs. Tried running it off that bat, no dice. Closed both davinci and the command window to try again. Still no dice. Near as I could tell, all of the errors are the same as my first comment, wit the exception of `File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\Modules\DaVinciResolveScript.py", line 36, in <module>
    raise ImportError("Could not locate module dependencies")` after the first file.
I can pop in the whole log up to where it starts repeating if you want. Haven't given it a proper look yet, and I have no idea what to look for outside of different. Could also try a restart before I reinstall davinci.

**Comment by octimot** [comment]
Could you zip and drop here the StoryToolkit log file (usually C:\Users\[user name]\StoryToolkitAI\app.log ) ?

**Comment by 01Bookworm01** [comment]
I was just double checking my `C:\Program Files\Blackmagic Design\DaVinci Resolve` path as well. All I have there is an audio folder for fairlight. Is that normal? When I install most things, I usually say no to them with the default path and install them instead in their own little folder that I make for them to live in. Could that be causing interference?

**Comment by 01Bookworm01** [comment]
Also sure. Just a sec

**Comment by 01Bookworm01** [comment]
[app.zip](https://github.com/octimot/StoryToolkitAI/files/9902033/app.zip)
Here's the log

**Comment by octimot** [comment]
Got it! Nothing wrong there except a GPU memory issue when you tried to transcribe using the large model (this model might require more than 8GB of VRAM, so if you absolutely think you need it, I recommend doing it via CPU, but it's going to be slow on non M1 machines).

So the log tells me that everything should be ok with the requirements / installation.

But, this...

> I was just double checking my C:\Program Files\Blackmagic Design\DaVinci Resolve path as well. All I have there is an audio folder for fairlight. Is that normal? When I install most things, I usually say no to them with the default path and install them instead in their own little folder that I make for them to live in. Could that be causing interference?

...this is most likely the problem.

You definitely need to point Python to the correct location of your Resolve Script Lib, which is usually in the folder where you installed Resolve.

The easiest (but hackiest way) is to modify DaVinciResolveScript.py, on line 24 and simply add the correct path (but use \\ instead of \ to properly escape the path).

The most elegant would be to add the path to the environment variables, but I'm not sure how that's going to work if you're using a non-standard Resolve installation folder.

**Comment by 01Bookworm01** [comment]
Okay, I've been trying to find where the resolve script lib is and I haven't been able to find it where I think it should be. Mind letting me know it's exact name and extension, as long as what usually lives around it?

**Comment by octimot** [comment]
I think it's fusionscript.dll and it should be wherever you installed Resolve.

**Comment by 01Bookworm01** [comment]
Yep, I see it. Was literally looking for something called "resolve script lib" or similar. 
So with the path, I replace `    path = "C:\\Program Files\\Blackmagic Design\\DaVinci Resolve\\"` with  `"    path = "C:\video editing\Davinci studio PAID\\"` ? Does it have to be changed with IDLE or can changing the script to a .txt, do the change and swapping back to .py work? Because for whatever reason the option to open it with Idle is not showing, even after a restart. It was there before my python reinstall though

**Comment by octimot** [comment]
Yes, save to .txt then rename to .py and it should work as long as it's called `DaVinciResolveScript.py` and nothing else. Python code is basic text.

**Comment by 01Bookworm01** [comment]
Tried it with the above change and everything is the exact same. It just won't connect to resolve. There's nothing that should be changed in the "get resolve" script in toolkit or anything anywhere else? I can try to do the environment variables, I know how to get to it, I'll just need somewhat specific instructions.

**Comment by octimot** [comment]
> File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\Modules\DaVinciResolveScript.py", line 36, in <module> raise ImportError("Could not locate module dependencies")

If this is still the error that you get, StoryToolkit finds `DaVinciResolveScript.py` and from there it's up to Blackmagic's script to find what it needs to start the API, so, unfortunately there's not much we can do from the tool side. Again, using a non-standard Resolve installation folder could mess things up, but I can't say for sure that that is the source of your problem on your machine.

What exactly did you write on line 24 of DaVinciResolveScript.py?

**Comment by octimot** [comment]
All forward slashes should be doubled on that line to properly escape them ( `\\` instead of `\` ): 
`path = "C:\\video editing\\Davinci studio PAID\\"`

It's unlikely that that is the problem, but we should make sure...

**Comment by 01Bookworm01** [comment]
It turns out that you should go for longshots sometimes. That bloody `\\`  was the issue including it fixed it.
Tested it as well to make sure it ran and it saved the timeline as a mp4 as it should and transcribed as it should. It took 100 seconds to translate 10 minutes,  so it's pretty damn good.

So note for any future morons I guess: If the `DaVanciResolveScript` cannot be found, make sure that it's actually pointing to where `fusionscript.dll` lives and not where it thinks it lives, and to use `\\` instead of `\` when changing the path.

**Comment by octimot** [comment]
> So note for any future morons 

:)))

I'm glad that it works!! Don't forget to check for overwrites in case you update Resolve and it stops working.

Actually this feedback regarding non-standard Resolve installation folders is important even if it's not an issue with the tool per se. The Resolve API is quite picky and not easy to navigate if you're not into Python stuff.  Thanks for the patience to report it!

I'll try to update the windows installation instructions soon, but as you see it may differ from machine to machine... Hopefully we'll compile a standalone .exe file soon.
