### ISSUE TITLE
Segementation Fault 19.4

### ISSUE THREAD

**Issue by danini1705** [octimot/StoryToolkitAI#121]
**Describe the bug**
<img width="575" alt="image" src="https://github.com/octimot/StoryToolkitAI/assets/19955147/f979f531-1a3a-4a44-9c0a-f11abe5c7e93">

**To Reproduce**
I am opening StoryToolkitAI via Terminal & Standalone, it doesn't seem to work and giving me an error

**Expected behavior**
I expect it work
<img width="260" alt="image" src="https://github.com/octimot/StoryToolkitAI/assets/19955147/c24c4135-55d5-4c91-b6f4-c8d79ea5953b">

**Log file**
Please include the app.log file - you can find it by clicking on File -> Configuration Directory

**Screenshots**
If possible, add screenshots to help explain your problem.

**System (please complete the following information):**
 - Mac OS Moneterey newest Version
 - Python 3.11
 - StoryToolkitAI Version 19.4

**Comment by octimot** [comment]
That's weird. Are you running this on an M1 Mac?

**Comment by danini1705** [comment]
Yes I am.

<img width="699" alt="image" src="https://github.com/octimot/StoryToolkitAI/assets/19955147/47849ba0-80e6-489c-8bc0-240986a115cc">

**Comment by octimot** [comment]
Ok, if version 0.19.4 worked on your Mac before, please try to delete the .app file, unzip it again from the downloaded archive file and try to start the app again.

It could be that the app bundle got corrupted for some reason...

Let me know if this works!

**Comment by danini1705** [comment]
I did that once already (or twice) it didn't work :/

**Comment by danini1705** [comment]
I installed NoFWL which is ChatGPT for Desktop but locally with an API

**Comment by danini1705** [comment]
It works now. I reinstalled it and removed the folder in my user folder
