### ISSUE TITLE
Can't save the preferences

### ISSUE THREAD

**Issue by danini1705** [octimot/StoryToolkitAI#122]
Now that the program works again, apparently, I can't save my preferences.

MacOS Monterey Newest Version
M1 Max 64 GB Ram

Version 19.4

**Comment by danini1705** [comment]
Update I could only save the preferences when I already transcribed something

**Comment by octimot** [comment]
We received more reports about this and it looks like it has something to do with new installs.

The workaround seems to be indeed doing something (transcribing / searching / etc.) which creates a fresh config.json file and allows the preferences to be saved.

We'll look into it soon!!

**Comment by octimot** [comment]
Fixed in v 0.19.5
