### ISSUE TITLE
Unable to find module DaVinciResolveScript from $PYTHONPATH

### ISSUE THREAD

**Issue by irazzam** [octimot/StoryToolkitAI#13]
Hi, I've just installed StoryToolkitAI on Windows 10 by following your detailed instruction. Inside the virtual environment, I ran the app. Then it shows this:

`INFO: Running StoryToolkitAI version 0.16.16`
`INFO: Using cuda for Torch / Whisper.`
`Unable to find module DaVinciResolveScript from $PYTHONPATH - trying default locations`

![Screenshot 2022-11-03 172053](https://user-images.githubusercontent.com/77427613/199696862-7a7e1059-250f-4a3b-b3a7-8bfd926fb5ef.jpg)

I'm quite new to running app with Python (I'm using Python 3.9 from Windows Store), did I miss something? My Davinci Resolve Studio's external scripting setting is set to Local

**Comment by irazzam** [comment]
Sorry, had to mark this as closed. I changed the Environment Variable for PYTHONPATH to Resolve's folder

`C:\ProgramData\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\Modules`

The error won't show anymore, but the app won't start. Might have to reinstall Python according to on issue #9 suggestion

**Comment by octimot** [comment]
Hey there! 

I'll add some additional info in issue #9 to keep everything related in one place.
