### ISSUE TITLE
Avid Text export failed when frame number for TC start is 00

### ISSUE THREAD

**Issue by Momomio** [octimot/StoryToolkitAI#132]
Hello,

As always, this last version of StoryToolkit is awesome, but I have one little bug :(

I'm on version 0.19.5 on Windows 10 and when I export as an Avid Text with a frame number for the TC start at "00", the export failed (for example, with a base 25, "09:40:17:00"). The file is created with the header, but after that it's empty.
For my transcription, I use wave file exported from Avid.

This is the error from the terminal window : 

> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "tkinter\__init__.py", line 1921, in __call__
>   File "storytoolkitai\ui\menu.py", line 215, in <lambda>
>   File "storytoolkitai\ui\toolkit_ui.py", line 7009, in button_export_as_avid_ds
>   File "storytoolkitai\core\toolkit_ops\transcription.py", line 2056, in write_avid_ds
>   File "storytoolkitai\core\toolkit_ops\transcription.py", line 2025, in format_timecode_line
>   File "timecode\__init__.py", line 83, in __init__
>     raise ValueError("``start_seconds`` argument can not be 0")

Is it also possible to modify the TC start with an option in the menu in addition to the export menue for Avid Text ? This way it can be changed for the .srt file also or if (and only if, but it never happened) I put the wrong TC when exporting as an Avid Text.

**Comment by octimot** [comment]
Hey!

I thought this was fixed, but I'll look into it! 

The Timecode Start 00:00:00:00 is problematic since the timecode module we use in python doesn't allow 0 frames, but I'll come up with a fix!

> Is it also possible to modify the TC start with an option in the menu in addition to the export menue for Avid Text ? This way it can be changed for the .srt file also or if (and only if, but it never happened) I put the wrong TC when exporting as an Avid Text.

This is on the todo list. We're going to add the option to change the timecode info for each transcription file, together with other settings.

Cheers!

**Comment by octimot** [comment]
The `00:00:00:00` error should have been fixed with version 0.23.0!

Plus, the timecode handling should be improved.

@Momomio Feel free to open this again in case something is weird on your end.

Cheers!
