### ISSUE TITLE
error launching in Monterey (intel)

### ISSUE THREAD

**Issue by grandosegood** [octimot/StoryToolkitAI#135]
hey all,

 i have installed python, but get this error when trying to open, according to terminal

ImportError: dlopen(/Applications/StoryToolkitAI.app/Contents/Resources/lib/python3.10/PIL/_imaging.cpython-310-darwin.so, 0x0002): tried: '/Applications/StoryToolkitAI.app/Contents/Resources/lib/python3.10/PIL/_imaging.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64h)))

**Comment by octimot** [comment]
I believe you're trying to open the app made for non-Intel macs on an Intel mac.

We'll try to make the Intel version available on the next update but it's damn hard work!

Cheers
