### ISSUE TITLE
Invisible buttons GUI

### ISSUE THREAD

**Issue by Djaygo** [octimot/StoryToolkitAI#143]
**Describe the bug**
After installation of the project, and running:
`python storytoolkitai`
The GUI stays dark/gray, there are clickable buttons but the GUI elements are invisible

**To Reproduce**
1. Go to StoryToolkitAI
2. Run on python storytoolkitai
3. See blank screen

**Expected behavior**
Visible GUI elements.

**Screenshots**

![Screenshot 2023-12-05 at 11 25 04](https://github.com/octimot/StoryToolkitAI/assets/10053770/dc97aa9f-85a5-44a6-b2ed-921dbafc28a5)

**System (please complete the following information):**
 - OS: Mac OS 14.1.1 (23B81)
 - Python versions installed on machine: [3.10.11, 3.9.18]
 - StoryToolkitAI Version: 0.19.16

**Comment by octimot** [comment]
Could you post the last lines in the log file (starting with -------------- Platform ...)?

**Comment by Djaygo** [comment]
Hi @octimot,

After  adding `export PATH="/usr/local/opt/tcl-tk/bin:$PATH"` to my .zshrc . The problem was solved, the previous installation of python 3.10.11 and 3.9.18 were using tkinter 8.5, now it is using 8.6 which shows a correct GUI

**Comment by octimot** [comment]
Great! 

Just for future reference, did you re-install Python recently or updated your Mac OS? Or what do you think lead to the removal of the environment variable?

**Comment by Djaygo** [comment]
I recently updated my Mac OS to 14.1.1 (23B81).. but I am not a tkinter user so I am not aware if it the env variable was set or required anywhere else. Thought brew would have added this to my path after install tcl-tk so python would not use the systems installation which is older.

**Comment by octimot** [comment]
Right, makes sense...

If you hit other similar errors, I would recommend re-installing Python and re-creating the virtual environment since some other packages might be missing their linked files after the update.
