### ISSUE TITLE
Can't open story toolkit

### ISSUE THREAD

**Issue by aldeniel** [octimot/StoryToolkitAI#146]
![Знімок екрана 2023-12-12 110520](https://github.com/octimot/StoryToolkitAI/assets/123870416/00327fbe-3935-41cf-9e09-ceb47f91cc70)

**Comment by octimot** [comment]
Do you have Resolve Studio or the free version?
And is it installed in the standard folder?

Cheers!

**Comment by aldeniel** [comment]
I have Studio version, yes is installed in the standard folder!

**Comment by aldeniel** [comment]
![зображення_2023-12-12_111909319](https://github.com/octimot/StoryToolkitAI/assets/123870416/f234fec8-5abf-40fa-adcd-c90ad5245d94)

**Comment by octimot** [comment]
> ![зображення_2023-12-12_111909319](https://private-user-images.githubusercontent.com/123870416/289807500-f234fec8-5abf-40fa-adcd-c90ad5245d94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzM0MzEsIm5iZiI6MTcwMjM3MzEzMSwicGF0aCI6Ii8xMjM4NzA0MTYvMjg5ODA3NTAwLWYyMzRmZWM4LTVhYmYtNDBmYS1hZGNkLWM5MGFkNTI0NWQ5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwOTI1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzNlMmM3MTNlOTRhOTBlODdhODgyNGRhN2M1N2ZjY2E3NmQ3MjA4MWJiN2VmMDU2NmM3NjYyOTgyY2UwNjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yvwZ6c2LByzu1xFkuTILWPf_1O1fXvIkmuVG8ZV69n4)

This error seems different and might not be connected with the previous one - it looks like this is connected to what rights your user has and it might mean that you have to run the setup with elevated rights (as admin)

> I have Studio version, yes is installed in the standard folder!

To continue on the thread of the previous error:
Do you have Python 3.10 installed on your system? Resolve needs it if you want to connect to the its API.

**Comment by aldeniel** [comment]
I have Pyhton 3.12, i need only 3.10?

**Comment by aldeniel** [comment]
I've deleted Python 3.12 and installed 3.10 and it works. Problem is solved. Thank you!
