### ISSUE TITLE
Advanced Voice Recognition and Tagging System for Multi-Speaker Audio Files

### ISSUE THREAD

**Issue by chris-hughes1** [octimot/StoryToolkitAI#147]
This enhancement will be particularly beneficial for transcribing meetings, interviews, gaming sessions, and podcasts involving multiple speakers, enabling users to distinguish who is speaking at any given time easily.

**Comment by octimot** [comment]
The Speaker Recognition/Diarization is top on the todo list - after we finish some new Assistant features.

What do you mean by "Advanced"? And how do you see the "tagging system"?

Cheers!

**Comment by chris-hughes1** [comment]
Mainly these: 

Advanced Speaker Recognition: Utilizes high-end technology for precise identification of individual speakers in complex audio.
Tagging System: Automatically labels audio segments with speaker names for easy tracking in recordings.

**Comment by octimot** [comment]
We're currently testing speaker change detection, so this will probably be available in version 0.23 or 0.24:

<img width="998" alt="Screenshot 2024-01-08 at 14 41 41" src="https://github.com/octimot/StoryToolkitAI/assets/64348499/7c1f9c34-660b-4ea8-8691-0768363022b4">

However, actual speaker recognition is a bit more complex, and I'm not sure that this can be done locally without many changes to the tool. It's planned though!

**Comment by octimot** [comment]
I've added [Speaker Detection](https://github.com/octimot/StoryToolkitAI/blob/main/FEATURES.md#speaker-detection) via Ingest or Transcription window with version 0.23.0

As I mentioned in the docs, the model is basic, but it does try to match speakers throughout the transcription. A more advanced implementation will come at some point!

Cheers

**Comment by chris-hughes1** [comment]
Amazing! Thank you! Do I need to re-download to get this feature? I didn't see a way to directly update to version 0.23.0 from Storytoolkit

**Comment by octimot** [comment]
Right now version 0.23.0 is available by [installing from source](https://github.com/octimot/StoryToolkitAI/blob/main/INSTALLATION.md#installing-the-tool-from-source-git-version)

A standalone release is coming in a few days as an early release for [Patreon members,](https://www.patreon.com/StoryToolkitAI) but we'll make it available publicly on the next version release.

Cheers!
