### ISSUE TITLE
Updating via 'git pull' not working, 'wrong number of arguments, should be 2'

### ISSUE THREAD

**Issue by PantsResewn** [octimot/StoryToolkitAI#156]
Whenever I run the 'git pull' command in the installation file it gives me 
fatal: detected dubious ownership in repository at 'C:/Users/name/Videos/Videos/Ai magic/StoryToolkitAI'
'C:/Users/name/Videos/Videos/Ai magic/StoryToolkitAI' is owned by:
     'S-1-5-32-544'
but current user is:
     'S-1-5-21-1680518411-127109467-3483647412-1003'
To add an exception for this directory, call:
     git config --global --add safe.directory 'C:/Users/name/Videos/Videos/Ai magic/StoryToolkitAI'

And when I run it it says:
error: wrong number of arguments, should be 2
usage: git config [ < options > ]

And then a big long list of things

System 
 - OS: Windows 10
 - Python versions installed on machine: 3.10.11
 - StoryToolkitAI Version 0.22.0

This is probably an easy fix, I just have no clue what to do, and I'm completely out of my depths with this.

**Comment by octimot** [comment]
The error message you're encountering is related to a security feature in Git which checks the ownership of the directory against the current user running the command. In your case, Git is detecting a mismatch between the owner of the repository and the current user. Maybe you installed with another user?

You can either try the recommended command again - but make sure you have the single quotes around the folder path and the exact syntax:
```
git config --global --add safe.directory 'C:/Users/name/Videos/Videos/Ai magic/StoryToolkitAI'
```

Or, simply re-install in another folder: [see this](https://github.com/octimot/StoryToolkitAI/blob/main/INSTALLATION.md#windows) (but you can skip step 4).

Cheers!

**Comment by PantsResewn** [comment]
That actually helped, but in a slightly round about way. I had to run the command as an admin and it worked perfectly. I feel very stupid not to have tried that sooner. Thanks!
