### ISSUE TITLE
After restarting the program error "can't find '__main__' module in 'C:\\Users\\benia\\Desktop\\StoryToolkitAI\\storytoolkitai'"

### ISSUE THREAD

**Issue by Benosik** [octimot/StoryToolkitAI#157]
After restarting the program running with activate.bat it does not see the files __main__.py
And when I manually go into the directory, this file is there. I have to run it manually then, but then I don't have the CUDA option.

![1](https://github.com/octimot/StoryToolkitAI/assets/77340272/f4330764-573a-4791-adb0-2ab7364a401d)
![2](https://github.com/octimot/StoryToolkitAI/assets/77340272/952f2632-1f5c-416c-9f9d-21a3c86963b7)

[Uploading app.log…]()

**Comment by octimot** [comment]
It's hard to tell from the two screenshots, but it could be that you're trying to execute from inside the installation, not from the folder where you did the initial `git clone`

The folder structure should look like this:
```
YOUR_INSTALLATION_FOLDER
+- StoryToolkitAI
+- venv
```

You have to be in `YOUR_INSTALLATION_FOLDER` (whatever the name is in your case) when you do `py StoryToolkitAI\storytoolkitai`, not in `YOUR_INSTALLATION_FOLDER\StoryToolkitAI`

I hope this makes sense.

Cheers!

**Comment by Benosik** [comment]
![3](https://github.com/octimot/StoryToolkitAI/assets/77340272/86209fd1-3653-4d7c-a621-64315875142d)
I use this startup procedure, I enter the root folder of StoryToolkitAI to run "venv" while in "venv" I run the command py... and there is a mistake 

![4](https://github.com/octimot/StoryToolkitAI/assets/77340272/b650133b-6b5d-4c46-98bf-12280973197e)

**Comment by octimot** [comment]
You have to be inside the first `StoryToolkitAI` folder when you execute the start command. From what I can tell, right now you are executing from the `Desktop` folder.

So try a `cd StoryToolkitAI` before the `py` command - that is your installation folder.

Cheers

**Comment by octimot** [comment]
I've improved the instructions, see this: https://github.com/octimot/StoryToolkitAI/blob/main/INSTALLATION.md#on-windows

Cheers!
