### ISSUE TITLE
Shift-click on Transcribe timeline to open pre-existing render - file type issue

### ISSUE THREAD

**Issue by rdacode** [octimot/StoryToolkitAI#16]
I like the idea of being able to use the already-rendered, audio-only file from a first transcription pass to do a new transcription. The problem seems to be that the auto-render that StoryToolkitAI does generates an (audio-only) .mov file, and the dialog that comes up when you Shift-click the Transcribe Timeline button is filtered to only .mp4, .wav, .mp3, so the existing .mov file cannot be selected.

**Comment by octimot** [comment]
> dialog that comes up when you Shift-click the Transcribe Timeline button is filtered to only .mp4, .wav, .mp3, so the existing .mov file cannot be selected.

I'll try to remove that limitation asap.

> StoryToolkitAI does generates an (audio-only) .mov file,

This is a bit weird. It should render out .wav files. Do you have the option to select "Wave" as Format and "Linear PCM" in the audio tab in the Deliver Page in Resolve?

**Comment by rdacode** [comment]
Ah, the Audio-only preset seems to default to Quicktime on my system. If I change it to .WAV, it works as expected. I wonder if it's a difference in the default between Mac and Windows?

**Comment by octimot** [comment]
You're right! It's the same on all platforms.

I completely forgot that we have a custom preset called transcription_WAV on our systems that is renderong Wave / Linear PCM.

If you create that, the tool should select it automatically, so you leave the Audio Only preset as it was.

I'll check to see if there's a specific reason why I didn't write the code to create the preset automatically.
