### ISSUE TITLE
Speechbrain error

### ISSUE THREAD

**Issue by clpStephen** [octimot/StoryToolkitAI#162]
**Describe the bug**
I'm getting an error when identifying speakers.:

ERROR: Unable to execute task <bound method ToolkitOps.speaker_detection of <storytoolkitai.core.toolkit_ops.toolkit_ops.ToolkitOps object at 0x0000021F8F30BB20>> for queue item Transcriptionof012124_AMY&TAMMYOTF.mov(SpeakerDetection)-1709226897.1966403
Traceback (most recent call last):
  File "C:\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\core\toolkit_ops\processing_queue.py", line 739, in execute_item_tasks
    kwargs = task(**{**kwargs, **item})
  File "C:\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\core\toolkit_ops\toolkit_ops.py", line 1502, in speaker_detection
    for resulting_segments, speaker_embeddings in detect_speaker_changes(
  File "C:\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\core\toolkit_ops\speaker_diarization.py", line 101, in detect_speaker_changes
    model = PretrainedSpeakerEmbedding("speechbrain/spkrec-ecapa-voxceleb", device=torch.device(torch_device))
  File "C:\StoryToolkitAI\venv\lib\site-packages\pyannote\audio\pipelines\speaker_verification.py", line 754, in PretrainedSpeakerEmbedding
    return SpeechBrainPretrainedSpeakerEmbedding(
  File "C:\StoryToolkitAI\venv\lib\site-packages\pyannote\audio\pipelines\speaker_verification.py", line 245, in __init__
    raise ImportError(
ImportError: 'speechbrain' must be installed to use 'speechbrain/spkrec-ecapa-voxceleb' embeddings. Visit https://speechbrain.github.io for installation instructions.

**To Reproduce**
WEll it completed the Transcription but failed on Speaker ID.

**Expected behavior**
It should attempt to ID speakers.
[app.log](https://github.com/octimot/StoryToolkitAI/files/14451793/app.log)

**Log file**
Please include the app.log file - you can find it by clicking on File -> Configuration Directory

**Screenshots**
If possible, add screenshots to help explain your problem.

**System (please complete the following information):**
 - OS: Windows 10
 - Python versions installed on machine: 3.10
 - StoryToolkitAI Version: 0.24.0

**Additional context**
Would installing speechbrain locally fix it or is this related to the new update?

**Comment by octimot** [comment]
This looks weird, since speechbrain should be installed by pyannote.

Could you execute the following command:

```
C:\StoryToolkitAI\venv\Scripts\python.exe -m pip list
```

You should see `pyannote.audio` and `speechbrain` in the list. Please copy and paste the list here too.

If you don't see the two packages, it means that something weird happened when you installed the requirements. 

So you should try this again:

```
C:\StoryToolkitAI\venv\Scripts\python.exe -m pip install -r C:\StoryToolkitAI\StoryToolkitAI\requirements.txt
```

And see if you get any errors.

Cheers!

**Comment by clpStephen** [comment]
I do see those on the list:

Package                 Version
----------------------- -----------
aiohttp                 3.9.3
aiosignal               1.3.1
alembic                 1.13.1
antlr4-python3-runtime  4.9.3
anyio                   4.3.0
asteroid-filterbanks    0.4.0
async-timeout           4.0.3
attrs                   23.2.0
audioread               3.0.1
blis                    0.7.11
catalogue               2.0.10
certifi                 2024.2.2
cffi                    1.16.0
charset-normalizer      2.1.1
click                   8.1.7
clip                    1.0
cloudpathlib            0.16.0
colorama                0.4.6
coloredlogs             15.0.1
colorlog                6.8.2
confection              0.1.4
contourpy               1.2.0
customtkinter           5.1.3
cycler                  0.12.1
cymem                   2.0.8
darkdetect              0.8.0
decorator               4.4.2
distro                  1.9.0
docopt                  0.6.2
dtw-python              1.3.1
einops                  0.7.0
exceptiongroup          1.2.0
ffmpeg-python           0.2.0
filelock                3.8.0
flatbuffers             23.5.26
fonttools               4.49.0
frozenlist              1.4.1
fsspec                  2024.2.0
ftfy                    6.1.3
future                  0.18.3
greenlet                3.0.3
h11                     0.14.0
httpcore                1.0.4
httpx                   0.27.0
huggingface-hub         0.21.1
humanfriendly           10.0
HyperPyYAML             1.2.2
idna                    3.4
imageio                 2.34.0
imageio-ffmpeg          0.4.9
iniconfig               2.0.0
Jinja2                  3.1.3
joblib                  1.3.2
julius                  0.2.7
kiwisolver              1.4.5
langcodes               3.3.0
langdetect              1.0.7
lazy_loader             0.3
librosa                 0.10.1
lightning               2.2.0.post0
lightning-utilities     0.10.1
llvmlite                0.42.0
Mako                    1.3.2
markdown-it-py          3.0.0
MarkupSafe              2.1.5
matplotlib              3.8.3
mdurl                   0.1.2
more-itertools          10.2.0
moviepy                 1.0.3
mpmath                  1.3.0
msgpack                 1.0.7
multidict               6.0.5
murmurhash              1.0.10
networkx                3.2.1
numba                   0.59.0
numpy                   1.26.4
omegaconf               2.3.0
onnxruntime             1.17.1
openai                  1.12.0
openai-whisper          20231117
opencv-python           4.9.0.80
optuna                  3.5.0
packaging               21.3
pandas                  2.2.1
patchify                0.2.3
pillow                  10.2.0
pip                     24.0
platformdirs            4.2.0
pluggy                  1.4.0
pooch                   1.8.1
preshed                 3.0.9
primePy                 1.3
proglog                 0.1.10
protobuf                4.25.3
pyannote.audio          3.1.1
pyannote.core           5.0.0
pyannote.database       5.0.1
pyannote.metrics        3.2.1
pyannote.pipeline       3.0.1
pycparser               2.21
pydantic                1.10.8
Pygments                2.17.2
pyparsing               3.0.9
pyreadline3             3.4.1
pytest                  8.0.2
python-dateutil         2.8.2
pytorch-lightning       2.2.0.post0
pytorch-metric-learning 2.4.1
pytz                    2024.1
PyYAML                  6.0
regex                   2022.9.13
requests                2.31.0
resampy                 0.4.2
rich                    13.7.0
ruamel.yaml             0.18.6
ruamel.yaml.clib        0.2.8
safetensors             0.4.2
scikit-image            0.22.0
scikit-learn            1.4.1.post1
scipy                   1.12.0
semver                  3.0.2
sentence-transformers   2.4.0
sentencepiece           0.2.0
setuptools              69.1.0
shellingham             1.5.4
six                     1.16.0
smart-open              6.4.0
sniffio                 1.3.1
sortedcontainers        2.4.0
soundfile               0.12.1
soxr                    0.3.7
spacy                   3.7.4
spacy-langdetect        0.1.2
spacy-legacy            3.0.12
spacy-loggers           1.0.5
speechbrain             1.0.0
SQLAlchemy              2.0.27
srsly                   2.4.8
sympy                   1.12
tabulate                0.9.0
tensorboardX            2.6.2.2
thinc                   8.2.3
threadpoolctl           3.3.0
tifffile                2024.2.12
tiktoken                0.6.0
timecode                1.3.1
tokenizers              0.15.2
tomli                   2.0.1
torch                   2.1.2
torch-audiomentations   0.11.1
torch-pitch-shift       1.2.4
torchaudio              2.1.2
torchmetrics            1.3.1
torchvision             0.16.2
tqdm                    4.66.2
transformers            4.38.1
typer                   0.9.0
typing_extensions       4.7.0
tzdata                  2024.1
urllib3                 2.2.1
wasabi                  1.1.2
wcwidth                 0.2.13
weasel                  0.3.4
wheel                   0.42.0
yarl                    1.9.4

**Comment by octimot** [comment]
Could you please try to install `speechbrain 0.5.16`. It looks like they made an update and it might have broken some stuff...

```
pip uninstall -y speechbrain
pip install speechbrain==0.5.16
```
 
Also, in case you get a `OSError: [WinError 1314` or similar, you might need to run the Command prompt with administrator privileges once to download the Speaker Detection model.

**Comment by clpStephen** [comment]
That has done the trick, thanks!
