### ISSUE TITLE
Able to launch only once

### ISSUE THREAD

**Issue by thormolio** [octimot/StoryToolkitAI#166]
I installed the windows version of the latest patreon release. Used it, everything worked amazing. Quit the program, unable to launch it again.
Restarted PC, still not working.
Uninstalled software, installed again, still not working.
Uninstalled, installed in a different folder, still not working.
No errors, no messages, nothing. One I try to launch the app - nothing happens. Task manager shows no STAI process running.

Would like it to work ;) But seriously, maybe you can help me provide more relevant information, like some kind of system logs r sth?

Windows 11
No Python installation
STAI latest patreon version

**Comment by octimot** [comment]
Hey there!

There are two things that you can try out:
### Option A
1. Go to the StoryToolkitAI configuration folder ("C:\Users\YOURUSERNAME\StoryToolkitAI"
2. Open app.log and look for anything weird
3. If you don't have any privacy concerns regarding revealing your user name, system info etc., drop it here and we can take a look.

### Option B
1. Press Start -> enter "cmd" (opens command prompt)
4. Go to the folder where StoryToolkitAI was installed - should be something like "C:\Users\YOURUSERNAME\AppData\Local\Programs\StoryToolkitAI\"
5. Drag the file StoryToolkitAI.0.23.2.WIN.CUDA.exe into the Command Prompt window you've opened
6. Hit enter in the command prompt
7. See if you get any weird messages

Also:
1. Do you have any anti viruses that might block the execution or is Windows Defender reporting anything?
2. Can you check if [api.storytoolkit.ai](https://api.storytoolkit.ai) is accessible from your location? The app uses this URL to check for updates and validate your API Key.
3. Make sure you really don't have a weird Python version installed by typing `py` or `python` or `python3` in Command Prompt.

Cheers!
