### ISSUE TITLE
Ffmpeg & DAvinci Resolve variables not found after installing from binary on Windows 10

### ISSUE THREAD

**Issue by KonradRychlewski** [octimot/StoryToolkitAI#17]
Dear all,

I installed ffmpeg using choco and tested it. I can run ffmpeg commands just fine. Unfortunately, when I try to run the StoryToolkitAI exe after extracting the folder with the binary for Windows 10, I only get the below screen flashing for a short while and disappearing.

![StoryToolkitAI screenshot](https://user-images.githubusercontent.com/118057729/201474902-9e692a87-27c5-40b8-a20b-3ec6945b7472.jpg)

Thanks so much for any advice. I need to admit I am not an expert user of Windows. Davinci Resolve 18.1 is installed the preferences are also set as advised, allowing local scripts to run.

**Comment by octimot** [comment]
Hey there!

The warnings that you see are not critical and would not shut down the app in normal circumstances!

Most likely you have another Python installation or similar that is messing up with the Resolve API. Did you even install Python on your machine?

Could you open up a command prompt and type `python --version`, `python3 --version` and `py --version` one after the other? Let's see what you get.

**Comment by KonradRychlewski** [comment]
Neither the Power Shell nor the command line return anything. If I only type python, the Microsoft app store is being launched. Installing Python has not been mentioned in the installation instruction for the binary which is we I concluded that the executable might have Python bundled in. Would you recommend to install Python 3.9 as mentioned in the "manual" installation guide?

**Comment by tetsujin28** [comment]
Hi
I have exactly the same problem.
I have Python version 3.10.6 already installed on W11 and I used the executable version of StoryToolkitAI, I tried to modify the environment variables of FFMPEG (which I installed with Choco) without success.

**Comment by octimot** [comment]
> Neither the Power Shell nor the command line return anything.
That's good! You don't need any sort of Python installed to run the standalone version!

With a command prompt open, could you drag and drop the .exe file there and then execute it to see if you get any other error on exit?

**Comment by octimot** [comment]
> I have Python version 3.10.6 already installed on W11 and I used the executable version of StoryToolkitAI, I tried to modify the environment variables of FFMPEG (which I installed with Choco) without success.

FFMPEG is not the problem there - if you're only seeing a `warning` it means that it's not critical and most likely FFMPEG was found on the system. If FFMPEG wasn't found, you'd get an `error`

> I have Python version 3.10.6 already installed on W11

This might be problematic for the Resolve API, depending how you installed it on the system.

As I was suggesting earlier, try to drop the .exe file in a command prompt and execute it there, to catch the exit error.

Most likely in both situations some sort of environment variable / path is confusing the Resolve API modules.

Let's try to get to the bottom of it!

**Comment by KonradRychlewski** [comment]
The behaviour is similar. Only difference: instead of the command line / power shell closing, the window remains open, but I am returned to the path which I started the program from. So if I was at c: and tried to run the toolkit, the initial response with the warnings would be identical. After 1 minute, without any additional notification, I would be back at c: in the prompt.

**Comment by KonradRychlewski** [comment]
I uninstalled ffmpeg, installed it again and tried to run StoryToolkitAI again, no luck.
![StoryToolkitAI screenshot2](https://user-images.githubusercontent.com/118057729/201505965-d91a17a9-d6d0-452a-8b69-1a04d5f5af0e.jpg)

**Comment by octimot** [comment]
@KonradRychlewski 
As I was saying earlier, ffmpeg has nothing to do with this if it's installed! A `warning` will not cause a crash in the tool.

What will cause a sys.exit() or crash is a messed up environment that might "confuse" the Resolve API.

Just for the sake of it, try to install Python 3.9 on your system, but only from [the official Python website](https://www.python.org/downloads/). Do not use the Microsoft Store or any other website to download that package! The purpose of this is just to addresse the weirdness on your machine as the new installation might clean up any corrupt paths etc. The tool will not use said Python, but the one that is contained in the release.

@tetsujin28 
If you have any other Python installation besides 3.9 and you don't need it, try yo uninstall.

**Comment by octimot** [comment]
By the way, it's very likely that this kind of crash would happen when trying to run any other software / integration that uses the Resolve API since the Resolve scripts are not working correctly on your machine. In other words, it probably has nothing to do with StoryToolkitAI.

One silly question: is your Resolve installed at the standard location (C:\Program Files\Blackmagic Design\DaVinci Resolve)?

**Comment by KonradRychlewski** [comment]
Yes, never changed any Black Magic install paths. Everything is where you mentioned. Can this have something to do with the latest 18.1 version of Davinci Resolve? I upgraded streight to 18.1, skipping 18.0.

**Comment by octimot** [comment]
> Can this have something to do with the latest 18.1 version of Davinci Resolve?

No, we have the tool running on 18.1 on all our machines here (both Windows and MacOS).

**Comment by Paddywack0** [comment]
Having the same problem as above. I didn't seem to have python installed so followed your instructions to install Python 3.9.15 and although I still get the WARNING FFMPEG_BINARY env variable is empty. Looking for ffmpeg in PATH.
The App seems to open now and seems to connect with Resolve. Just trying to work out how to access and transcribe within Resolve. This is on a Win10 z820 with CUDA

**Comment by DonnumFractus** [comment]
> Having the same problem as above. I didn't seem to have python installed so followed your instructions to install Python 3.9.15 and although I still get the WARNING FFMPEG_BINARY env variable is empty. Looking for ffmpeg in PATH. The App seems to open now and seems to connect with Resolve. This is on a Win10 z820 with CUDA. All working perfectly now.

This ultimately worked for me as well, I had to uninstall 3.10 and reinstall 3.9.15.
