### ISSUE TITLE
Installation process of  Windows git version of StoryToolkitAI 0.24.0 reinstalls non-Cuda version of Torch

### ISSUE THREAD

**Issue by bbqrooster** [octimot/StoryToolkitAI#170]
**Describe the bug**
Installation process of Windows git version of StoryToolkitAI 0.24.0 reinstalls non-Cuda version of Torch. This makes StoryToolkitAI 0.24 cannot use NVIDIA card even if one is available.

**To Reproduce**
1. Follow the installation process of Windows git version of StoryToolkitAI 0.24.0 including the installation of Torch with CUDA 2.2.1 
cu118
2. Execute venv\Scripts\python StoryToolkitAI\storytoolkitai 1st time
3. You can see the installation of storytookitai removes Torch with CUDA 2.21 cu118 and replaces it with Torch without CUDA version 2.1.2
4. Running StoryToolkitAI 0.24 confirms that the CUDA option is not available.

**Installation log file
[Installation Log.txt](https://github.com/octimot/StoryToolkitAI/files/14739444/Installation.Log.txt)

**Expected behavior**
I expect Torch with CUDA should not be replaced with Torch without CUDA.

**System (please complete the following information):**
 - Windows 11
 - Python versions 3.10.0rc2
 - StoryToolkitAI Version 0.24

**Additional context**
Anything else that is relevant here.

**Comment by octimot** [comment]
Hey, thanks for pointing this out! 

This is most likely because the tool does a `pip install -r requirements.txt` on that particular update.

We'll add a step which will check if there's CUDA support or not and let it decide which version to keep/install.

Cheers!

**Comment by bbqrooster** [comment]
Thanks

**Comment by octimot** [comment]
Fixed with https://github.com/octimot/StoryToolkitAI/commit/25eb44bc628e6cbd0715f57013ffc84fe826c1cd
