### ISSUE TITLE
Progress bar for model download

### ISSUE THREAD

**Issue by The3IC** [octimot/StoryToolkitAI#173]
Minor UI nit. As the model download takes quite some time, it would be nice to get a progress bar in the Queue window.

**Comment by octimot** [comment]
We tried to do this before, however each model is downloaded by its own package - for e.g. transcription models are downloaded by Whisper, indexing models are downloaded using Huggingface Hub etc.

Unfortunately, most of these packages don't offer any programmatic way of tapping into the download progress.

The only way to see what's happening behind the hood is if you use the git version of the tool. In that case, some of these packages do show you a progress bar / percentage directly in Terminal / CMD.
