### ISSUE TITLE
problem installing requirements: Could not find a suitable TLS CA certificate bundle

### ISSUE THREAD

**Issue by pantau000** [octimot/StoryToolkitAI#176]
D:\temp\StoryToolkitAI>venv\Scripts\activate.bat

(venv) D:\temp\StoryToolkitAI>pip install -r StoryToolkitAI\requirements.txt
Collecting openai-whisper@ git+https://github.com/openai/whisper.git@ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab (from -r StoryToolkitAI\requirements.txt (line 28))
  Using cached openai_whisper-20231117-py3-none-any.whl
Collecting clip@ git+https://github.com/openai/CLIP.git@a9b1bf5920416aaeaec965c25dd9e8f98c864f16 (from -r StoryToolkitAI\requirements.txt (line 34))
  Using cached clip-1.0-py3-none-any.whl
Collecting customtkinter@ git+https://github.com/octimot/CustomTkinter.git@a2a8c37dd8dac1dee30133476596a5128adb0530 (from -r StoryToolkitAI\requirements.txt (line 38))
  Cloning https://github.com/octimot/CustomTkinter.git (to revision a2a8c37dd8dac1dee30133476596a5128adb0530) to c:\users\user\appdata\local\temp\pip-install-gdajuvck\customtkinter_1e4b0026376944f69a7f4c124c75fc0b
  Running command git clone --filter=blob:none --quiet https://github.com/octimot/CustomTkinter.git 'C:\Users\User\AppData\Local\Temp\pip-install-gdajuvck\customtkinter_1e4b0026376944f69a7f4c124c75fc0b'
  Running command git rev-parse -q --verify 'sha^a2a8c37dd8dac1dee30133476596a5128adb0530'
  Running command git fetch -q https://github.com/octimot/CustomTkinter.git a2a8c37dd8dac1dee30133476596a5128adb0530
  Resolved https://github.com/octimot/CustomTkinter.git to commit a2a8c37dd8dac1dee30133476596a5128adb0530
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      ERROR: Could not install packages due to an OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Program Files\PostgreSQL\16\ssl\certs\ca-bundle.crt

      WARNING: There was an error checking the latest version of pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: There was an error checking the latest version of pip.

**Comment by octimot** [comment]
Based on the error, it might be that your PostgreSQL installation messed up the Python environment, by making it look into the wrong certificate bundle.

Did you recently install or update PostgreSQL?

You could try to reinstall pip in the virtual environment, with something like:
```
python -m pip install --upgrade pip
``` 

If this doesn't work, you'll have to point python to the correct .crt certificate bundle (which is usually in the Python installation dir).

Cheers!

**Comment by pantau000** [comment]
thanks very much, in fact it was a postgres problem...

**Comment by gorm3531** [comment]
How did you fix it? Help me...

**Comment by gorm3531** [comment]
I have the same problem with postgres

**Comment by wojtek19022** [comment]
I have the same problem as @gorm3531. Please help guys 

<img width="1081" height="99" alt="Image" src="https://github.com/user-attachments/assets/552ac525-cd72-44bd-87dc-973e26854723" />

**Comment by octimot** [comment]
@wojtek19022 Have you tried the solution that I recommended above?

Cheers!

**Comment by wojtek19022** [comment]
> @wojtek19022 Have you tried the solution that I recommended above?
> 
> Cheers!

I'm sorry for not extending my comment.

I resolved this issue by:
1. Search for **cacert.pem** file in venv directory
2. Seach for **CURL_CA_BUNDLE** variable
3. Set directory to **cacert.pem** file to **CURL_CA_BUNDLE** envirnmental variable.

In my case command '''set CURL_CA_BUNDLE=path to cacert.prm''' resolved this issue

This issue occured on Windows 10 when I installed all of my local instances of PostgreSQL.
