### ISSUE TITLE
No "Max. Characters/Words per Line" option

### ISSUE THREAD

**Issue by mustafamohsen** [octimot/StoryToolkitAI#177]
**Describe the bug**
I use the current 0.24.1 version on Mac. Yet, I can't find the [Max. Characters/Words per Line](https://github.com/octimot/StoryToolkitAI/blob/main/FEATURES.md#transcription-settings) setting. I know that the documentation mentions that it's outdated. But I couldn't find the option elsewhere

**Screenshots**
![CleanShot 2024-04-18 at 12 02 02@2x](https://github.com/octimot/StoryToolkitAI/assets/29289923/c6fb016e-e78a-45b8-aeba-a2722980778d)

**System:**
 - OS: MacOS 14
 - Python versions installed on machine: 3.10
 - StoryToolkitAI Version 0.24.1

**Additional context**
I'm connected to Davinci Resolve API

**Comment by octimot** [comment]
Hey there!

The setting is only available if you enable Increased time precision - see [this](https://github.com/octimot/StoryToolkitAI/blob/main/FEATURES.md#transcription-settings) 

Cheers
