### ISSUE TITLE
Start transcribing gives this RuntimeError: CUDA out of memory on Windows 10 with an Nvidia GTX 1650

### ISSUE THREAD

**Issue by elijahbee** [octimot/StoryToolkitAI#18]
Getting CUDA out of memory errors as follows:

> ERROR: Traceback (most recent call last):
  File "app.py", line 4659, in transcribe_from_queue
  File "app.py", line 4918, in whisper_transcribe
  File "whisper\__init__.py", line 113, in load_model
    return model.to(device)
  File "torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "torch\nn\modules\module.py", line 602, in _apply
    param_applied = fn(param)
  File "torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.46 GiB already allocated; 0 bytes free; 3.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

![image](https://user-images.githubusercontent.com/1111337/201652143-c8556996-7952-4b4f-af6c-fe1693e392da.png)

SYSTEM DETAILS ATTACHED 

[DxDiag.txt](https://github.com/octimot/StoryToolkitAI/files/10002753/DxDiag.txt)

**Comment by octimot** [comment]
You need around 8GB of VRAM on your GPU to transcribe using the medium model. I recommend selecting CPU as Device in the Transcription Settings window.

This will be slow, but you will get the transcription eventually.

Alternatively, you can try to use the base model (or base.en, if it's an English audio) - although you might not get the perfect transcript back.

**Comment by octimot** [comment]
You could also try the medium.en model if you're transcribing English audio, although I think 4GB are too low for that too.

I will update the README, thanks for the feedback BTW!

**Comment by elijahbee** [comment]
Thanks for the quick reply, I've tried medium.en and got the same error. However, the base.en model worked with CUDA, and finished transcribing a 00:23:14 long video in 659 seconds which is 0.47x ... and I'm very impressed!!! 

I'll give you feedback after I've run it on another device with an 8GB GPU. 

THANK YOU!!!
