### ISSUE TITLE
AVID DS Export - Blank TXT file created

### ISSUE THREAD

**Issue by KeoPostUK** [octimot/StoryToolkitAI#183]
Whenever I export a transcript as an AVID DS file the resulting txt file is blank. 

System: Ventura 13.6.6 M2 Max

**Comment by octimot** [comment]
Please provide more context

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Log file**
Please include the app.log file - you can find it by clicking on File -> Configuration Directory

**System (please complete the following information):**
 - Python versions installed on machine: [e.g. 3.9.13]
 - StoryToolkitAI Version [e.g. 0.17.11]
 
 Cheers!
