### ISSUE TITLE
Issue's with my PC after installing standalone version for windows

### ISSUE THREAD

**Issue by Shaygeee** [octimot/StoryToolkitAI#188]
After installing the standalone version for windows, all my files have been deleted from user and my PC is acting up right now 

All Documents, Desktop, Downloads and i guess more from app data have been deleted 
![image](https://github.com/user-attachments/assets/36312a85-07b1-45a5-9173-2ea1ddb56e67)

**Comment by octimot** [comment]
Unfortunately there's no way to reproduce this based on the limited info you sent us. Could it be that you selected the Downloads folder as the installation dir?
