### ISSUE TITLE
integration with resolve doesnot work

### ISSUE THREAD

**Issue by zeevbin** [octimot/StoryToolkitAI#193]
**Describe the bug**
after integrate the toolkitai with resolve API it just vanishes
i dont know where to look for it
resolve is in programfiles
sould i do somthing in resolve
thanks

**Comment by zeevbin** [comment]
the toolkit is working from another folder- from the users
maybe this is the problem?

wht should i see if every thing works fine with resolve?
where sould i find the script or integration?

**Comment by zeevbin** [comment]
the toolkit works fine without the resolve integration
but this is not good enough for me
please help

**Comment by octimot** [comment]
Please search for related issues before posting. Thanks
