### ISSUE TITLE
I cannot find the INTEL version of this release. Could you help me?

### ISSUE THREAD

**Issue by HerbertKeller66** [octimot/StoryToolkitAI#195]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Log file**
Please include the app.log file - you can find it by clicking on File -> Configuration Directory

**Screenshots**
If possible, add screenshots to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows 10, MacOS 12.6]
 - Python versions installed on machine: [e.g. 3.9.13]
 - StoryToolkitAI Version [e.g. 0.17.11]

**Additional context**
Anything else that is relevant here.

**Comment by octimot** [comment]
Please be more specific in your request. Thanks
