### ISSUE TITLE
Install fails on MacOS 12.7.6

### ISSUE THREAD

**Issue by BristolBEAT** [octimot/StoryToolkitAI#198]
**Describe the bug**
I've installed successfully many times in the past via the terminal route. However recently on MacOS 12.7.6 after all the processes successfully installing, I get an issue which reads "ERROR FFmpeg not found on this machine. Reading of certain audio and video files will not work. Please install it and try again"

**To Reproduce**
I try to reinstall 'brew install ffmpeg' which installs again but doesn't resolve the problem

**Expected behavior**
Should launch the StoryTookkitAI interface

**System (please complete the following information):**
 - OS: MacOS 12.6.7
 - Python versions installed on machine: 3.10
 - StoryToolkitAI Version  0.24.3

**Comment by octimot** [comment]
Dumb question, but have you tried to uninstall and reinstall ffmpeg, not just install it?
```
brew uninstall ffmpeg
brew install ffmpeg
```

Also, could you provide a full log file to see where the error lies? The ffmpeg issue shouldn't prevent the tool from starting.
