### ISSUE TITLE
moviepy 2.0 has introduced breaking changes (ModuleNotFound moviepy.editor)

### ISSUE THREAD

**Issue by Coxyca** [octimot/StoryToolkitAI#202]
**Describe the bug**
MoviePy recently upgraded to v2.0, introducing breaking changes which prevent StoryToolkit from starting/running.

**To Reproduce**
1. Follow the installation guide and run _venv/bin/python StoryToolkitAI/storytoolkitai_
2. A _ModuleNotFound_ error appears (moviepy.editor)

**Expected behavior**
StoryToolkitAI should start running.

**System (please complete the following information):**
 - OS: Windows 10
 - Python versions installed on machine: 3.10.11
 - StoryToolkitAI Version 0.24.3

**Additional context**
It seems like I had the unfortunate timing of installing StoryToolkit almost the same day MoviePy decided to push a major update.

I first tried to update the import in media.py with _from moviepy import VideoFileClip, AudioFileClip_ and it did get the app to start properly but only then I realized other bugs were happening ("_File file.mp4 does not have a valid video stream_" on every single video I tried to ingest).

I downgraded moviepy back to 1.0.3 and everything works as intended (note that to do that I also had to downgrade setuptools to 69.5.1 because pip was throwing an error otherwise). If [updating ](https://zulko.github.io/moviepy/getting_started/updating_to_v2.html) to moviepy 2 isn't particularly useful for the project, it might be good to set a strict 1.0.3 requirement.

**Comment by octimot** [comment]
Thanks for noticing this!

I just pushed https://github.com/octimot/StoryToolkitAI/commit/841b5bcb85f1ebb7fe7114962a68251ea5c752a9 which keeps the moviepy requirement strict until we test if we need the new functionality.
