### ISSUE TITLE
Debug file is built with error

### ISSUE THREAD

**Issue by BaGRoS** [octimot/StoryToolkitAI#22]
Log file in the 

c:\Users\[USER NAME]\StoryToolkitAI\app.log

is generated with some error: After block of information before adding next block is added 
2022-11-15 11:43:02,744 - StAI - DEBUG:
without any data.

> 2022-11-15 11:42:20,770 - StAI - INFO: FFMPEG found at C:\ProgramData\chocolatey\bin\ffmpeg.EXE (app.py:6922)
> 2022-11-15 11:42:20,785 - StAI - INFO: Using cuda for Torch / Whisper. (app.py:4446)
> 2022-11-15 11:42:20,785 - StAI - DEBUG: MotsResolve module initialized. (mots_resolve.py:42)
> 2022-11-15 11:42:20,801 - StAI - INFO: Resolve API module found and loaded (mots_resolve.py:177)
> 2022-11-15 11:43:02,744 - StAI - DEBUG: 
> --------------
> Platform: Windows 10
>  Platform version: 10.0.22621
>  OS: 10 10.0.22621 SP0 Multiprocessor Free  ('', '', '')  
>  running Python 3.9.13.final.0
> -------------- (app.py:140)
> 2022-11-15 11:43:03,120 - StAI - DEBUG: All package requirements met. (app.py:160)
> 2022-11-15 11:43:03,122 - StAI - INFO: [1m[4mRunning StoryToolkitAI version 0.17.4  (app.py:6464)
> 2022-11-15 11:43:03,218 - StAI - DEBUG: Looking for ffmpeg in env variable. (app.py:6895)
> 2022-11-15 11:43:03,218 - StAI - DEBUG: FFMPEG_BINARY env variable is empty. Looking for ffmpeg in PATH. (app.py:6902)
> 2022-11-15 11:43:03,220 - StAI - DEBUG: Checking ffmpeg binary: C:\ProgramData\chocolatey\bin\ffmpeg.EXE (app.py:6914)
> 2022-11-15 11:43:03,256 - StAI - DEBUG: FFMPEG exit code: 1 (app.py:6919)
> 2022-11-15 11:43:03,256 - StAI - INFO: FFMPEG found at C:\ProgramData\chocolatey\bin\ffmpeg.EXE (app.py:6922)
> 2022-11-15 11:43:08,098 - StAI - INFO: Using cuda for Torch / Whisper. (app.py:4446)
> 2022-11-15 11:43:08,099 - StAI - DEBUG: MotsResolve module initialized. (mots_resolve.py:42)
> 2022-11-15 11:43:08,114 - StAI - INFO: Resolve API module found and loaded (mots_resolve.py:177)
> 2022-11-15 11:48:13,738 - StAI - DEBUG: 
> --------------
> Platform: Windows 10
>  Platform version: 10.0.22621
>  OS: 10 10.0.22621 SP0 Multiprocessor Free  ('', '', '')  
>  running Python 3.9.13.final.0
> -------------- (app.py:140)
> 2022-11-15 11:48:14,124 - StAI - DEBUG: All package requirements met. (app.py:160)
> 2022-11-15 11:48:14,124 - StAI - INFO: [1m[4mRunning StoryToolkitAI version 0.17.4  (app.py:6464)
> 2022-11-15 11:48:14,398 - StAI - DEBUG: Looking for ffmpeg in env variable. (app.py:6895

Like:
> 2022-11-15 11:43:08,114 - StAI - INFO: Resolve API module found and loaded (mots_resolve.py:177)
> 2022-11-15 11:48:13,738 - StAI - DEBUG: 

next line is added 5 minutes later.

**Comment by octimot** [comment]
This is probably generated by a premature crash, closing for now.
