### ISSUE TITLE
no gui

### ISSUE THREAD

**Issue by gsakatch** [octimot/StoryToolkitAI#26]
I have installed everything, and the cmd screen says i'm Running StoryToolkitAI version 0.17.6.2.  Using cpu for Torch /Whisper.
But i don't get any fancy 2000 era gui opening.

I'm not sure what to do next.

Running windows 10 with Nvidia RTX A5000

**Comment by octimot** [comment]
Hey there!

Most likely there's something weird happening on your environment, so to get to the 2000s inspired GUI (which is definitely excessive for your A5000 :-D ), please see the discussion here https://github.com/octimot/StoryToolkitAI/issues/25 and feel free to continue the thread over there.

I'm closing this issue and re-opening that one, to keep all things related with Windows app start there.

Cheers
