### ISSUE TITLE
No module named 'librosa'

### ISSUE THREAD

**Issue by visualfeast** [octimot/StoryToolkitAI#27]
Windows 10 Pro 21H2, python 3.9.13, Resolve Studio 18.1.1 w/ external scripting on Local. StoryToolkitAI installed via the INSTALLATION.md instructions, running in venv.

Running py StoryToolkitAI\app.py gives:
```
Traceback (most recent call last):
  File "J:\resolve\StoryToolkitAI\app.py", line 24, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'
```

Tried `pip install librosa` as well; did not help.

**Comment by octimot** [comment]
This is almost always related to how python is installed on your system and if pip is executed by the correct python version/executable.

We went through this process on another issue: https://github.com/octimot/StoryToolkitAI/issues/19#issuecomment-1315177347

To make it easier for you, I'll try to summarize that conversation below.

Assuming you have activated the virtual environment and that you are in the folder where you git cloned the tool, you should do the following:

Try to find out exactly where is py or python running from, by executing each of them individually and getting the executable path:

```
py
import sys
print(sys.executable)
```
and same for python
```
python
import sys
print(sys.executable)
```
Whichever is inside your (venv) environment (i.e. it's file location is inside the venv folder), that's the one you need to use to do the pip install

Then, try to install the requirements via 
```
py -m pip install -r StoryToolkitAI\requirements.txt
```

Or 
```
python -m pip install -r StoryToolkitAI\requirements.txt 
```
(depending which command runs inside your virtual environment)

As a general rule when in comes to compatibility with the tool, if you're not using `py` on windows it most likely means that you haven't used the official Python installer or that you've unchecked/checked some features during its installation which is generally not a good idea.

Let me know if this helps.

**Comment by visualfeast** [comment]
Thanks, that was it. A 3.10 was also installed and causing the issue.
