### ISSUE TITLE
"Keep on Top" creates UI issue when there is a pop-up choose box

### ISSUE THREAD

**Issue by Europa2010AD** [octimot/StoryToolkitAI#28]
With the transcript window open and "Keep on Top" enabled, any button that would pop out a choose box requiring further actions -- e.g. pressing 'T' to re-transcribe -- the choose box would appear behind the main window and there is no indication to the user this is happening, other than the OS error alert sound when the user tries to click somewhere on the screen (it would appear as if the app is unresponsive, but it's not -- it's just stuck with the choose box appearing behind the window)

**Comment by octimot** [comment]
Thanks for the feedback! I'll try to recreate that as soon as I have some time. Do you see this happening with other windows too?

**Comment by octimot** [comment]
These issues have been solved with the new UI, starting with version 0.19+
