### ISSUE TITLE
FP16 not supported on CPU, slow speeds.

### ISSUE THREAD

**Issue by shoefrado** [octimot/StoryToolkitAI#3]
I'm not very experienced with ML stuff, so apologies if this is all normal or not within the scope of your extension.

Getting this error when running Transcribe Timeline after the audio render:
```
UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
```

Also getting very slow speeds (possibly due to the error?); 200-250 seconds for a 13 second clip.

System specs: 
Mac Pro 2019
3.2GHz 16-core Intel Xeon W
192GB RAM
AMD Radeon W6800X Duo 32GB

**Comment by octimot** [comment]
Hey there!

No need to apologize! The message is a simple warning that lets you know that it switched to FP32 precision. Unfortunately FP16 precision for Whisper is not supported on CPUs (as the warning says), but only on CUDA based GPUs.

As I know, FP16 precision (although lower half than FP32) would be significantly faster, so this may be one of the reasons why CPU processing is slower than GPU with this model.

Unfortunately we didn't get the chance to test it on Intel based machines without CUDA GPUs so I can't say why it's so slow. Based on what I know so far is that, on an 8-core M1 with 16GB RAM you get the transcription result in cca. 1.5x - 2x the length of the audio, but on a higher end RTX3080 8GB, you'll get them in 0.15 - 0.20x the length of the audio. 

Did you try to run the transcription on multiple timelines / files? Usually, the first time you run it, it also has to download the medium model which is around 1.5Gb in size.

Cheers!

**Comment by shoefrado** [comment]
Ah, that all makes sense. Unfortunately I've had similar speeds with multiple timelines; 15-20 times the length of the audio. Looks like AMD isn't supported by Whisper yet, and with ROCm being Linux only, that probably won't change anytime soon. 

Guess I'll have to run it on our NVIDIA windows machine or wait for our Mac Studio to arrive.

Thanks!

**Comment by octimot** [comment]
I've improved the loading of the model in the newest version, which means that after the first transcription, all the ones that follow should transcribe faster. 

I'm not sure how much of an improvement will be your end, but if you want to give it a try, just pull the latest version.
