### ISSUE TITLE
Installation file crashes(Win 10)

### ISSUE THREAD

**Issue by Nargot1** [octimot/StoryToolkitAI#30]
[app.log](https://github.com/octimot/StoryToolkitAI/files/10149291/app.log)
![image](https://user-images.githubusercontent.com/106655199/205510831-9a480c4f-f85b-4634-a6ec-9833e77ba03f.png)

**Comment by octimot** [comment]
Please see [this thread](https://github.com/octimot/StoryToolkitAI/issues/25) and feel free to re-open it in case the solution to reinstall Python doesn't work on your machine.

Cheers!

**Comment by Nargot1** [comment]
I have redownloaded python and ffmpeg. and still doesnt work.
