### ISSUE TITLE
Resolve API connection disabled (Standalone version 0.17.5) (non-standard Resolve folder)

### ISSUE THREAD

**Issue by 01Bookworm01** [octimot/StoryToolkitAI#31]
Tried running 0.17.5 and it would not connect to Resolve because it's not where Toolkit thinks it should be, and I haven't found anything to let me change the path it's looking at. Here's a screenshot of the exact issue:

![Screenshot 2022-12-09 084152](https://user-images.githubusercontent.com/116970101/206573236-6c149dde-8332-4dc2-8087-2d1952e7abc3.png)

I still managed to transcribe it by feeding Toolkit the audio file. This issue is absent from 0.17.1

As an aside, I have noticed that the transcripts across both versions have been identical, but that they has been a variety of small mistakes that I don't think it should be getting. It's more noticeable and understandable when I speak, as I tend to stutter and trip over my words a bit, but it happens to the others in the recording quite a bit as well. I'm not sure if it has something to do with audio quality or the length of the transcription or what, but it's something I feel that it's worth mentioning. I can other up the json file and video if you want so you can see for yourself. For context it's a dnd session that I'm transcribing, so it makes sense for some of the words to be wrong but not most of the ones that are.

**Comment by octimot** [comment]
Sorry for the late reply!!

Just to make sure that I understood correctly: 
1. Your Resolve installation is not in `C:\Program Files\Blackmagic Design\DaVinci Resolve`? Or it is, but Version 0.17.5 doesn't detect it there?
2. Version 0.17.1 was connecting with Resolve despite Resolve being installed in a non-standard folder? Or?

Cheers!

**Comment by 01Bookworm01** [comment]
Yes, my resolve installation is not in `C:\Program Files\Blackmagic Design\DaVinci Resolve`. I've already changed line 24 in `DaVinciResolveScript.py` to point to where it should be, but I'm not sure if the standalone version needs it. We went through all of this back in issue #12 anyway. The main point is that Version 0.17.5 is picky while Version 0.17.1 isn't regarding the install location.
