### ISSUE TITLE
 StoryToolkitAI How to use Large-v2 model？

### ISSUE THREAD

**Issue by ppoudd1** [octimot/StoryToolkitAI#32]
StoryToolkitAI How to use Large-v2 model？
I compared it StoryToolkitAI Large and whisper Large-v2,Two different outcomes,I Think StoryToolkitAI use old Large,How do I get StoryToolkitAI use Large-v2 model？

**Comment by octimot** [comment]
That's a good one! I'll look into it as soon as possible.

**Comment by octimot** [comment]
Are you using the standalone version or the git version of the tool?

For the git version, simply run this in your virtual environment:
```
pip install --upgrade --no-deps --force-reinstall git+https://github.com/openai/whisper.git
```

For the standalone version, we need to freeze it when we do a new release.

**Comment by pantau000** [comment]
is it still necessary to do this to work with the large model?

**Comment by octimot** [comment]
The newest versions fully integrate the latest openai-whisper packages, including support for the large-v2 model.
