### ISSUE TITLE
When transcribing got audio rendering problem

### ISSUE THREAD

**Issue by maaat68** [octimot/StoryToolkitAI#34]
When transcribing got audio rendering problem. It renders a white noise clip !
But when i re-render it in manual, it's ok and then i can transcribe at the second step of the script procedure !

on a DVR 18.1.1
Mac Intel version

**Comment by octimot** [comment]
Do you re-render the same render job in Resolve?

If yes, I think something might be wrong with Resolve.

**Comment by maaat68** [comment]
Yes! and i don't know where in the process that mess happen. With DVR 18.1 and StoryToolKit 0.17.5 it was ok and after the upgrade i had this issue!

**Comment by octimot** [comment]
After you upgraded Resolve? Maybe some audio channels need to be re-mapped. I think I saw this issue on the blackmagic forums.

**Comment by maaat68** [comment]
I found why now. The problem appears when it renders a vertical format (1080x1920) !

**Comment by octimot** [comment]
Unless you really need to use a specific format, I recommend using the transcription_WAV preset, read this: https://github.com/octimot/StoryToolkitAI#resolve-transcription_wav-preset

Cheers!
