### ISSUE TITLE
Clearing "queue" - how to cancel everything

### ISSUE THREAD

**Issue by BeeOu** [octimot/StoryToolkitAI#35]
Is it possible to clear the queue?
I have tried to restart it, but every time it wants to continue a job that I actually want to abort.
<img width="716" alt="queue" src="https://user-images.githubusercontent.com/120682799/207959849-170aea73-7bf0-46a7-ad5c-fd99544ba88d.png">

**Comment by octimot** [comment]
You can delete the entire queue by going to the StoryToolkitAI config folder and deleting the `transcription_queue.json` file.

I'll add a clear queue button soon!!

**Comment by BeeOu** [comment]
Thank you soo much.

**Comment by octimot** [comment]
Version 0.18.0 now adds the ability to cancel transcriptions from queue directly from the UI - see [changelog](https://github.com/octimot/StoryToolkitAI/blob/main/CHANGELOG.md).
