### ISSUE TITLE
Audio quality vs transcribe quality

### ISSUE THREAD

**Issue by BaGRoS** [octimot/StoryToolkitAI#4]
Please improve the saving of the rendered audio to the file. After changing from mp4 to mov the files are less well recognised by whisper.
BaGRoS

**Comment by octimot** [comment]
This is weird, on our end it works better with WAV compared to Quicktime mp4 and the pipelining to whisper is faster too:

After you render it out in Resolve, whisper takes over and converts it via ffmpeg to specs, which I believe are exactly WAV 16bit 48000 (see whisper/audio.py)

Do you have the latest version? I accidentally pushed the code which was loading the tiny model initially, but then pushed the medium again :-|

**Comment by BaGRoS** [comment]
or maybe this because CUDA, I have to test

**Comment by octimot** [comment]
> BTW: have a look [openai/whisper#259](https://github.com/openai/whisper/discussions/259)

That's interesting. You should be able to try it by simply uninstalling whisper and then installing it from the other repo.
