### ISSUE TITLE
What Transcribe Button?

### ISSUE THREAD

**Issue by jonathanljs** [octimot/StoryToolkitAI#41]
v 0.17.5.WIN, from expanded standalone. Feels like there ought to be more to the setup than just expanding the file...
So - what Transcribe button!? (Screencap attached.) All I get is a blank Powershell/Terminal window. Have uninstalled all instances of Python, and tried clean installs of both 3.11.1 and 3.9,12, all to no avail.
Have set external scripting use to local and am on Studio v 18.1.2
Windows 11, all up to date.
Only unusual thing is that I'm running a dual monitor setup.
Any thoughts?
Was very excited to try this...
![Screenshot 2023-01-02 184122](https://user-images.githubusercontent.com/55745688/210269189-0d5801ad-e998-4b17-9725-7d8ce5870c65.jpg)

**Comment by jonathanljs** [comment]
Well, I just went ahead and went the CLI route instead. That works. Shame about the standalone, though.

**Comment by vojtanethio** [comment]
I have the same problem 🙃

**Comment by jonathanljs** [comment]
> 

I suggest the manual (CLI or command line) install. It's a little intimidating if you're not used to doing that kind of thing, but it works and now everything is up and running. It's worth doing: this is going to be a big timesaver.

**Comment by octimot** [comment]
For windows, please look into the other install issues ([both closed or open](https://github.com/octimot/StoryToolkitAI/issues?q=windows+install)). If we're talking about the standalone version, it's most likely some other python install on your machine that is interfering with the tool. 

Feel free to open the specific issue that looks closest to what you're experiencing and continue the conversation there. Thanks!
