### ISSUE TITLE
Transcribe+Translate: how to correct original language file for better EN translation results?

### ISSUE THREAD

**Issue by qrevol** [octimot/StoryToolkitAI#43]
Hello dears,

I have been using StoryToolkitAI inside my DaVinci Resolve Studio 18 on a M1/16GB RAM MacBookPro and loving the transcription-translation results from Portuguese into English. Thank you for putting so much work into this wonderful API. 

Despite the high match results for generic language, content with unique words, such as people and place names, disciplinary scientific jargon, the machine-transcription and translation of course needs a lot of human correction. 

My question to the developers and community is about efficient ways to correct the original language texts and EN files in a way that you can somehow automate or semi-automate the correction process. In other words, I am trying to avoid the painstaking process of correcting words in all 4 files separately... the two files: srt and txt in original language and the English language srt and txt.

Also, after reading all instructions I am still a bit confused about the difference among running "Transcribe Timeline" first, then "Translate timeline to English"... in addition to having the option to select a "transcribe+translate" in the window that pops up upon selecting "Translate timeline to English". If I do "transcribe+translate" for a 10-min, video, I am getting both PT and EN files in about 17-min. which I think is really good, right?

Thank you so much for your replies!

Wishing everyone a healthy and happy 2023!
Vanessa

**Comment by octimot** [comment]
Hey Vanessa!

Sorry for the late reply - we're in a production since a few weeks, but we'll restart development most likely next week when we're back in the editing room.

In short, Whisper (the AI transcription module we're using) either does direct transcriptions or direct translations due to how it was trained. Therefore, when you select transcribe+translate in the tool, it will first do a transcription and then a separate translation operation (both based on the same audio data). It will never use the transcription result for the translation!

So, the best approach from the development point of view is to either allow the user to either fine-tune Whisper (with content related to its work) or to work out some sort of post-processing method which takes into account the corrections done on one of the languages and apply them to all others. This is already on our todo list, but need to fix some other stuff before, since the transcription part is only a small part of what the tool is supposed to be helping us with - the main part being the content search.

However, you're saying that you need to correct both TXT and SRT files. Why don't you simply do the corrections in the transcription edit window and then export from there?

Cheers

**Comment by qrevol** [comment]
Dear Octavian,
   
  
    
   
  
   Thank you so much for taking the time to reply to me with detailed help. Sorry to only now react, but I edit my film project alongside writing a dissertation and I was in writing mode. Now back into DaVinci to consider what you said.
   
  
    
   
  
   Please see my comments / questions in red below yours.
   
  
    
   
  
   Thank you in advance for your recommendations.
   
  
   Best wishes,
   
  
    
   
   
    
    
     Vanessa Ramos-Velasquez
     
    
     media artist • researcher • lecturer
     
    
     realçando experiências através da arte interdisciplinar
     
    
     ……………………………………………………………..
     
    
     Co-fundadora/Mitgründerin
     
    
     www.araraencantada.com.br
     
    
     ……………………………………………………………..
     
    
     www.quietrevolution.me
     
    
     ***@***.***
     
    
     Berlin mobile +49 (0)157 7922 9308
     
    
     ……………………………………………………………..
     
    
     Doktorandin, Bauhaus-Universität Weimar
     
    
     Bauhaus-Promotionsstipendiums 2018, 2019
     
    
     Thüringer Graduiertenförderung 2021, 2022
     
    
      
     
    
   
   
   
    On 1.2.23 11:31 CET Octavian Mot ***@***.***> wrote:
    
   
     
    
   
     
    
     
   Hey Vanessa! 
   Sorry for the late reply - we're in a production since a few weeks, but we'll restart development most likely next week when we're back in the editing room. 
   In short, Whisper (the AI transcription module we're using) either does direct transcriptions or direct translations due to how it was trained. Therefore, when you select transcribe+translate in the tool, it will first do a transcription and then a separate translation operation (both based on the same audio data). It will never use the transcription result for the translation! 
   So, the best approach from the development point of view is to either allow the user to either fine-tune Whisper (with content related to its work) or to work out some sort of post-processing method which takes into account the corrections done on one of the languages and apply them to all others.  
   
  
   I did not understand that. This post-processing at the moment is not automated, right? Even if I had to do it manually, how could I apply the corrections done in PT (transcription) and apply them to EN (translation), for example?
   
   
   This is already on our todo list, but need to fix some other stuff before, since the transcription part is only a small part of what the tool is supposed to be helping us with - the main part being the content search. 
   However, you're saying that you need to correct both TXT and SRT files. Why don't you simply do the corrections in the transcription edit window and then export from there? 
   
  
   Do you mean that if I correct the transcription in the transcription window, I can export this corrected file? This would simplify a bit... instead of exporting an incorrect file and opening it in Text Edit on Mac to do the corrections there, for example.
   
  
    
   
  
   And lastly, is it ok to update from DaVinci 18 Studio to 18.1.4 Studio or do you recommend waiting a while? 
   
  
    
   
  
   Thank you!!
   
   
   Cheers

**Comment by octimot** [comment]
Sorry for the late reply, this issue somehow got lost in the inbox...

If it's not too late, to edit transcriptions, you simply have to ALT+Click or OPT+Click on them and you can simply edit the words. [Here](https://github.com/octimot/StoryToolkitAI/blob/main/FEATURES.md#transcription-window-shortcuts) is a list of all the shortcuts available in the transcription window.

I'll close this issue for now, but feel free to reply back on it if you have other questions.

Cheers!

**Comment by qrevol** [comment]
Dear Octavian,
   
  
    
   
  
   Thank you so much for the info. It helps me a lot.
   
  
    
   
  
   Wishing you a lot of success in the project. I imagine it makes an immense contribution to the indie film production community. Is there a way to make a one-time contribution to your project?
   
  
    
   
  
   Best wishes for 2024.
   
  
    
   
   
    
    
     Vanessa Ramos-Velasquez
     
    
     media artist • researcher • lecturer
     
    
     realçando experiências através da arte interdisciplinar
     
    
      
     
    
   
   
   
    On 8.1.24 10:49 -03 Octavian Mot ***@***.***> wrote:
    
   
     
    
   
     
    
     
   Sorry for the late reply, this issue somehow got lost in the inbox... 
   If it's not too late, to edit transcriptions, you simply have to ALT+Click or OPT+Click on them and you can simply edit the words. Here is a list of all the shortcuts available in the transcription window. 
   I'll close this issue for now, but feel free to reply back on it if you have other questions. 
   Cheers!
