### ISSUE TITLE
Model Storage Location

### ISSUE THREAD

**Issue by PabloThi** [octimot/StoryToolkitAI#44]
First of all, thanks for building this! I haven't fully tested it yet but it's already amazing. I hope you keep working on it as well. I have a question regarding the model storage location, especially on Mac. Where can I find it, in case I need to delete files?

Thanks!

**Comment by octimot** [comment]
Hey, thanks for the feedback!

The models are stored in the `.cache` folder in your home directory. Open up terminal, then:
```
open ~/.cache
```

This should open a finder window directly in the cache folder.
