### ISSUE TITLE
Can't set time intervals outside 1 minute mark

### ISSUE THREAD

**Issue by irazzam** [octimot/StoryToolkitAI#45]
Hi, for some reason the time intervals won't accept time past 1 minute.
For example, I can transcribe a timeline set on 30.00 - 40.00. But I can't set anything past 59.00 second.
If I have a portion of timeline I want to transcribe, let's say at 40.00 - 01.23.00 , it wil not work. The terminal windows will say "ValueError: could not convert string to float: '01.23.00'"

**Comment by octimot** [comment]
This is because you need to use the value in seconds, not minutes:

1:20 is 80.00

**Comment by irazzam** [comment]
> This is because you need to use the value in seconds, not minutes:
> 
> 1:20 is 80.00

Ah, thank you so much! I'll mark this as closed
