### ISSUE TITLE
Rename whisper in requirements.txt to openai-whisper

### ISSUE THREAD

**Issue by bruce55** [octimot/StoryToolkitAI#47]
Trying to install StoryToolkitAI on a new computer and run into setup issues.

Turned out that OpenAI renamed the package to `openai-whisper`.

**Comment by octimot** [comment]
Thanks for the heads up! We've been stuck in production in the past weeks, but will get back on track with development asap next week.

Did you `pip install git+https://github.com/openai/whisper.git `? Does the tool work well with the new whisper package?

Cheers!

**Comment by octimot** [comment]
Solved. Version 0.17.7 is now updated to use `openai-whisper`. We will freeze that into the standalone version too soon.
