### ISSUE TITLE
I'm having some trouble with the virtual environment on step 7. Nothing happens.

### ISSUE THREAD

**Issue by Igor-Deoli** [octimot/StoryToolkitAI#49]
![Screenshot 2023-01-24 135431](https://user-images.githubusercontent.com/123500666/214383061-284edab8-d6bb-401d-b37b-e2045255180e.jpg)

All the previous steps worked alright.

**Comment by fwjlwo** [comment]
It seems you don't have pip configured in your environment. Try using "python3.9 -m pip install git+https://github.com/openai/whisper.git" and in all subsequent pip installations

**Comment by Igor-Deoli** [comment]
Thank you. I just noticed that there is no installer for 3.9 anymore. I assumed 3.11 would work just fine but that might be the problem.

**Comment by octimot** [comment]
Will look into this as soon as possible and update the documentation!

**Comment by octimot** [comment]
Whisper and some other packages don't work on Python >3.10. We recommend using 3.9 for now.

Also, version 0.17.7 is now updated to use `openai-whisper` - see new requirements.txt
