### ISSUE TITLE
Will there be a standalone version with large v2 model?

### ISSUE THREAD

**Issue by antonkarliner** [octimot/StoryToolkitAI#58]
Sorry if the question is dumb, but it seems that there were no updates in standalone versions for a while, so I'm wondering if it's worth to wait for an update.

**Comment by octimot** [comment]
Yes, an update is coming soon, but we want to pack some more updates besides the new whisper integration into it.

Unfortunately, compiling and testing the standalone versions takes a good amount of our time, so we can only afford to make it every few updates or so...

Cheers

**Comment by antonkarliner** [comment]
Understood. Thank you for the great work!
