### ISSUE TITLE
Using timecode for Time Intervals

### ISSUE THREAD

**Issue by Momomio** [octimot/StoryToolkitAI#62]
Hello,

Can you add the possibilitie to use timecode instead of seconds for the Time Intervals function ?

For exemple : 
00:03:20:00 - 00:03:36:17
00:34:42:10 - 00:35:42:16

**Comment by Momomio** [comment]
We are using it with Resolve and without too but we always know what framerate we're working with...

Could it be possible to autodetect the framerate with tools like [MediaInfo](https://mediaarea.net/fr/MediaInfo) or [ExifTool](https://exiftool.org/) ?

**Comment by octimot** [comment]
Not all files have timecode medatada in them unfortunatelly - especially if you're dealing with audio only, so for now it's easier if we just ask the user to enter the timecode info manually when it doesn't exist, as I mentioned before.

We're implementing more timecode features in the tool - like the ability to copy transcript segments to clipboard or send them to ChatGPT with timecode column etc. - and will get to this request too as soon as possible!

**Comment by octimot** [comment]
Time Intervals accept timecodes in the Transcription Settings window starting with version 0.18.3.

Thanks for the input @Momomio!
