### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by pantau000** [octimot/StoryToolkitAI#63]
Updates on the non-standalone tool
# on Windows
pip -r StoryToolkitAI\requirements.txt

does not work for me:
"no such option: -r"

**Comment by octimot** [comment]
Thanks for the feedback!! 

It should be `pip install -r StoryToolkitAI\requirements.txt`

I just corrected the instructions

**Comment by pantau000** [comment]
That was fast... Thanks!!

**Comment by pantau000** [comment]
"git pull" isn't working here:

(venv) C:\Python\StoryToolkitAI>git pull
fatal: not a git repository (or any of the parent directories): .git
