### ISSUE TITLE
Rust needed for source install

### ISSUE THREAD

**Issue by bxtdvd** [octimot/StoryToolkitAI#66]
Hi there! Thanks for putting together this great project!

I'm running a pretty fresh macOS Ventura install on an M1 machine, and my install from source errored out on step 7 due to missing Rust. While pip does tell you that's the problem, it's buried about a dozen lines up and kinda easy to miss if you don't know what to look for.

In INSTALLATION.md, I'd suggest adding Rust to the Homebrew install list. The following worked for me, although it's certainly not the only way:
`brew install rustup`
`rustup-init`
Hit `1` when prompted
`source "$HOME/.cargo/env"`

Thanks!

P.S. This looks similar to the error encountered in #40, but it appears the install instructions were [recently changed](https://github.com/octimot/StoryToolkitAI/commit/119f84a5a76d0a1b5bc2a0258c720b170fb652d4), and you're no longer linking to the Whisper install docs — which is where folks previously would've been told to install Rust.

**Comment by octimot** [comment]
That's a good point, thanks! 

I'll revert the modified instructions to keep whisper in a different step.
