### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by pantau000** [octimot/StoryToolkitAI#67]
"git pull" isn't working here:

(venv) C:\Python\StoryToolkitAI>git pull
fatal: not a git repository (or any of the parent directories): .git

**Comment by octimot** [comment]
It's important that you do the `git pull` in the directory where you did the first `git clone`.

If not, something might have been corrupted, so I recommend reinstalling.

**Comment by pantau000** [comment]
Thanks... Actually I did reinstall to be sure nothing gets corrupted. Still get the same error message:

Microsoft Windows [Version 10.0.19044.2728]
(c) Microsoft Corporation. All rights reserved.

C:\Program Files\StoryToolkitAI>git pull
fatal: not a git repository (or any of the parent directories): .git

C:\Program Files\StoryToolkitAI>

**Comment by octimot** [comment]
Can you execute `dir` and return the results here?

**Comment by pantau000** [comment]
Directory of C:\Program Files\StoryToolkitAI

11.03.2023  10:49    <DIR>          .
11.03.2023  10:49    <DIR>          ..
11.03.2023  11:18    <DIR>          StoryToolkitAI
11.03.2023  10:53    <DIR>          venv

**Comment by octimot** [comment]
What happens if you `cd StoryToolkitAI` and then perform `git pull` ?

**Comment by pantau000** [comment]
C:\Program Files\StoryToolkitAI>cd StoryToolkitAI

C:\Program Files\StoryToolkitAI\StoryToolkitAI>git pull
fatal: detected dubious ownership in repository at 'C:/Program Files/StoryToolkitAI/StoryToolkitAI'
'C:/Program Files/StoryToolkitAI/StoryToolkitAI' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-1535969142-1192740391-274321278-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory 'C:/Program Files/StoryToolkitAI/StoryToolkitAI'

**Comment by octimot** [comment]
I think there might be a folder permission problem. Maybe you created the folder with the admin user previously and now things are weird.

No idea how to help, but see this for more info:
https://medium.com/@thecodinganalyst/git-detect-dubious-ownership-in-repository-e7f33037a8f

**Comment by pantau000** [comment]
Reinstalled again, and put the StoryToolkitAI Folder on the non-system disk this time. Now everything worked. So it might have been because the C:\Program Files folder requires administration privileges.

Thanks again!
