### ISSUE TITLE
Searching low number of characters (e.g. Chinese) in .txt files

### ISSUE THREAD

**Issue by GypsyAcidQueen** [octimot/StoryToolkitAI#69]
Hi there,

First of all, wanted to say I absolutely love the plugin - I don't know how I ever worked without it.

I do a lot of editing in Chinese, in which one or two 'characters' generally make up a word. I have noticed that the search does not kick in until there are at least 3 'characters', meaning that most individual words in Chinese cannot be searched in a transcript currently. It didn't seem like this was an issue in previous versions, or maybe I just didn't notice it before, but it is definitely there in this verison. 

I wonder if this is something that could be fixed!

All best, Alex

**Comment by octimot** [comment]
Hey!

A previous update makes it so that the tool ignores all segments shorter than 2 characters to optimize for speed, considering that a lot of languages don't really have single character words, but it wasn't thought well enough. Thanks for pointing this out!

It will be fixed asap!

Question: currently, the phrases in the search are split split by punctuation marks. Do you find that it works well for Chinese - i.e., do you sometimes get multi-phrase results that aren't split when an end-of-phrase punctuation mark occurs?

Thanks

**Comment by GypsyAcidQueen** [comment]
Hi there,

Thanks so much for the quick response, really appreciated! And really appreciate the work you guys are putting in. 

I actually don't use the advanced search much for my workflow, I'm using basic ctrl+f style search mostly because I remember specific words in a long interview and I need to quickly jump around. I'll try testing it in the next few days and get back to you. 

Big love for your team!! If you're opening up donations let me know

**Comment by octimot** [comment]
Trying to solve the character limitation issue, but I realized that the limitation is only valid for .txt files. Did you see this happening on transcription files too? If so, could you send an example?

Thanks!

**Comment by GypsyAcidQueen** [comment]
> 

Hi there,

No you're absolutely right, that's my fault, I didn't realise that I was searching inside .txt files that day! 

All best, just signed up for the patreon! Let's get this community going.

**Comment by octimot** [comment]
Cool, thanks!!

We'll make the .txt file limitation flexible as soon as possible too.

**Comment by GypsyAcidQueen** [comment]
Hi again, sorry to reopen this but I think that the limitation is still in .transcript files in 17.16.2 (I only contribute 4 dollars to the patreon so don't have access to the latest version, not sure if it's been updated there yet). The search doesn't bring up results until at least a third character is typed

![image](https://user-images.githubusercontent.com/91021594/234748961-2719e2ec-2d12-4786-aeb2-037c73d46a2f.png)
![image](https://user-images.githubusercontent.com/91021594/234749000-635d60c0-17b9-4fd4-a8d6-e8f6d41b20f5.png)
![image](https://user-images.githubusercontent.com/91021594/234749053-15595f00-387c-409e-a88f-f9441c3a9446.png)
