### ISSUE TITLE
LLVM ERROR: Symbol not found: __svml_cosf8_ha

### ISSUE THREAD

**Issue by reckweb** [octimot/StoryToolkitAI#72]
I use the (wonderful!!) tool some times successful, also the standalone, but now it won't work.

Run Resolve 18.1.4. Build 9, but:

(venv) C:\Users\xxx\StoryToolkit>py StoryToolkitAI\app.py
INFO: Running StoryToolkitAI version 0.17.15
INFO: Using cpu for Torch / Whisper.
INFO: Resolve API module found and loaded
INFO: Resolve API module found and loaded
INFO: Starting to transcribe 2023-Kirschbaumbilder.mp3
INFO: Using cpu for Torch / Whisper.
INFO: Loading Whisper medium model.
INFO: Resuming transcription queue from file
INFO: Starting StoryToolkitAI GUI
INFO: Prompting user for render path.
INFO: Selected Whisper model is multilingual.
LLVM ERROR: Symbol not found: __svml_cosf8_ha

Win 10 64, CUDA 11.7.101 driver (Cuda not recognized)
Python 3.9.13

Like octimot says in an email, I make space (now 111GB) on drive C:, and I only have installed Python 3.9.13. Same issue.

**Comment by octimot** [comment]
Can you please try to execute `nvidia-smi.exe` and copy the output here?

**Comment by reckweb** [comment]
Tue Mar 21 16:48:13 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.94       Driver Version: 516.94       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P2200       WDDM  | 00000000:01:00.0  On |                  N/A |
| 49%   40C    P8     8W /  75W |    176MiB /  5120MiB |     18%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      4860    C+G   ...e\Current\LogiOverlay.exe    N/A      |
|    0   N/A  N/A     11520    C+G   ...nsole\TourBox Console.exe    N/A      |
+-----------------------------------------------------------------------------+

**Comment by octimot** [comment]
This might sound like a stupid question, but have you tried the transcription on an audio file that has worked in the past?

The only thing I can think of it no audio files work is to completely remove Python from your system and try to re-install.

The fact that it doesn't detect the CUDA GPU might also have to do with a recently updated driver, although we have the exact same driver and CUDA version on one of our editing machines and it works fine...

**Comment by reckweb** [comment]
Tried everything, the tool can open a transcript already made, search, etc. -- but as soon as I try to transcribe an audio file it aborts with the same error message. Changed driver, reinstalled python, torch is installed as stated. What else can I do?

**Comment by reckweb** [comment]
I reinstalled the standalone version, which now diligently transcribes a wav file. What a miracle. be happy again...

**Comment by octimot** [comment]
I'm glad you sorted it out...

It's hard to tell what exactly is causing the problem. I suspect that a full Python clean-up or re-install would help.

I will prepare an update for the standalone version soon also...

**Comment by octimot** [comment]
@reckweb 

Would you be so kind as to try the following commands in your virtual environment, in the non-standalone installation that didn't work?

```
pip uninstall torch torchaudio torchvision
pip cache purge
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
```

I just found a problem with CUDA machines that might be related to your issue!

**Comment by reckweb** [comment]
Thank you very much, but:
```
...
Successfully installed torch-2.0.0+cu117 torchaudio-2.0.1+cu117 torchvision-0.15.1+cu117
...
INFO: Selected Whisper model is multilingual.
LLVM ERROR: Symbol not found: __svml_cosf8_ha
...
```
Unfortunately didn't work. I'm very happy that I have the standalone...

**Comment by reckweb** [comment]
Tried the new standalone (v0.17.16 extra alpha) and got the **same error**. The old version still works fine.

**Comment by octimot** [comment]
Thanks for reporting this!

I suspect there's some sort of driver mismatch on your system.

What CPU is your system running on and do you happen to have _svml_dispmd.dll_ in _C:\Windows\System32_?

Cheers

**Comment by reckweb** [comment]
Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz   3.60 GHz
svml_dispmd.dll not there

LG

**Comment by octimot** [comment]
Unfortunately, I haven't seen this pop-up anywhere else, so I think it's a machine-specific issue.

If you're still hitting this issue even after the last updates, I recommend installing CUDA 11.8 using the installer from here:
https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local

And then trying to re-install torch using these commands:
```
pip uninstall torch torchaudio torchvision
pip cache purge
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118
```

Cheers!

**Comment by Rafal-TS** [comment]
Hi!
I have the same problem and have been struggling with it for a long time.
I have tried all your previous tips. Unfortunately, it was unsuccessful.

`INFO: Running StoryToolkitAI version 0.19.5 (standalone)
INFO: Starting StoryToolkitAI GUI
INFO: Loading Whisper large-v2 model.
INFO: Selected Whisper model "large-v2" is multilingual.
LLVM ERROR: Symbol not found: __svml_cosf8_ha
`
![image](https://github.com/octimot/StoryToolkitAI/assets/127836958/3894b979-d5a8-474a-bcbf-8129fc969c21)



The older version 0.17.5 works fine.
please help

**Comment by yinpeilin** [comment]
hello，guys，I meet the same problem when I use the another model, and it seems like a problem in librosa(I try that and my problem fixes ). Try to reinstall librosa may also fix your problem.
