### ISSUE TITLE
lines/words/characters/seconds per title

### ISSUE THREAD

**Issue by barzoock** [octimot/StoryToolkitAI#73]
A feature that allows you to adjust the number of lines/words/characters/seconds per title would be great.

I thought I could do it with "Initial Prompt" but it doesn't seem to work. If you can explain how (if possible), it would be great.

As well, it is not an issue, it is a feature request, I'm pretty new on Github, so I apologize for the incorrect tagging.

Thank you very much

**Comment by octimot** [comment]
Just replied on #42
