### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by Danielosaurs** [octimot/StoryToolkitAI#74]
When running: pip install -r StoryToolkitAI/requirements.txt, I get this error:
![Screenshot 2023-03-23 at 11 41 43](https://user-images.githubusercontent.com/128736174/227294255-7b84dd29-2e68-42aa-af42-265c0d0c5fb8.png)
I don't know how to fix it

**Comment by octimot** [comment]
You may need to install rust for openai-whisper, check this how-to:
https://www.rust-lang.org/learn/get-started

**Comment by Danielosaurs** [comment]
That worked! Thank you so much for making this wonderful tool! Did you learn how to code yourself? Or did you learn through a formal institution?

**Comment by octimot** [comment]
Cool, glad that it helped!

> Did you learn how to code yourself? Or did you learn through a formal institution?

It's just learning out of necessity... before AI takes over anyway :-))
