### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: torch

### ISSUE THREAD

**Issue by Momomio** [octimot/StoryToolkitAI#77]
Hello,

My transcription isn't working, I have a "failed" on the transcription log.

Here is the app.log with a "PermissionError" at the end

I'm on macOS Catalina.

> 2023-03-27 10:35:53,715 - StAI - DEBUG: 
> --------------
> Platform: Darwin 19.6.0
>  Platform version: Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
>  OS:     10.15.7 ('', '', '') x86_64 
>  running Python 3.9.13.final.0
> -------------- (app.py:147)
> 2023-03-27 10:35:54,072 - StAI - DEBUG: All package requirements met. (app.py:167)
> 2023-03-27 10:35:54,078 - StAI - DEBUG: Loading config file /Users/nodal2catalina/StoryToolkitAI/config.json. (app.py:11553)
> 2023-03-27 10:35:54,089 - StAI - INFO: Config setting api_token saved as "False"  (app.py:11497)
> 2023-03-27 10:35:54,089 - StAI - DEBUG: Loading config file /Users/nodal2catalina/StoryToolkitAI/config.json. (app.py:11553)
> 2023-03-27 10:35:54,089 - StAI - INFO: Updated config file /Users/nodal2catalina/StoryToolkitAI/config.json with api_token data. (app.py:11523)
> 2023-03-27 10:35:54,094 - StAI - INFO: Config file /Users/nodal2catalina/StoryToolkitAI/config.json saved. (app.py:11540)
> 2023-03-27 10:35:57,392 - StAI - INFO: [1m[4mRunning StoryToolkitAI version 0.17.16 (standalone) (app.py:11370)
> 2023-03-27 10:35:57,392 - StAI - INFO: Using cpu for Torch / Whisper. (app.py:8737)
> 2023-03-27 10:35:57,392 - StAI - DEBUG: MotsResolve module initialized. (mots_resolve.pyc:42)
> 2023-03-27 10:35:57,392 - StAI - DEBUG: Trying to load DaVinciResolveScript module... (mots_resolve.pyc:140)
> 2023-03-27 10:35:57,393 - StAI - DEBUG: Found DaVinci Resolve at the default location: /Applications/DaVinci Resolve/ (mots_resolve.pyc:205)
> 2023-03-27 10:35:57,393 - StAI - DEBUG: Unable to find module DaVinciResolveScript from PYTHONPATH - trying default locations next (mots_resolve.pyc:217)
> 2023-03-27 10:35:57,540 - StAI - INFO: Resolve API module found and loaded (mots_resolve.pyc:239)
> 2023-03-27 10:35:57,541 - StAI - DEBUG: Trying to load DaVinciResolveScript module... (mots_resolve.pyc:140)
> 2023-03-27 10:35:57,541 - StAI - DEBUG: DaVinciResolveScript module loaded from PYTHONPATH (mots_resolve.pyc:154)
> 2023-03-27 10:35:57,541 - StAI - INFO: Resolve API module found and loaded (mots_resolve.pyc:239)
> 2023-03-27 10:35:57,541 - StAI - WARNING: Resolve is not reachable. Retrying every few seconds. (app.py:11125)
> 2023-03-27 10:35:57,938 - StAI - DEBUG: Could not load StoryToolkitAI icon. (app.py:3001)
> 2023-03-27 10:35:57,941 - StAI - DEBUG: Running with TK 8.6.12 (app.py:3009)
> 2023-03-27 10:35:58,454 - StAI - INFO: Starting StoryToolkitAI GUI (app.py:3712)
> 2023-03-27 10:36:27,981 - StAI - WARNING: Resolve connection re-established. (app.py:11064)
> 2023-03-27 10:36:34,542 - StAI - DEBUG: Updated project settings file /Users/nodal2catalina/StoryToolkitAI/projects/TRANSCRIPT COSQUER/project.json. (app.py:11625)
> 2023-03-27 10:40:58,903 - StAI - DEBUG: Updated project settings file /Users/nodal2catalina/StoryToolkitAI/projects/TRANSCRIPT COSQUER/project.json. (app.py:11625)
> 2023-03-27 10:41:41,306 - StAI - INFO: Prompting user for render path. (app.py:8836)
> 2023-03-27 10:41:47,779 - StAI - DEBUG: No transcription log window exists. (app.py:5919)
> 2023-03-27 10:41:47,780 - StAI - INFO: Saving into /Users/nodal2catalina/Desktop/TRANSCRIPT COSQUER/untitled folder and starting render. (app.py:7224)
> 2023-03-27 10:41:47,924 - StAI - DEBUG: Found render preset transcription_WAV in available presets list in Resolve (mots_resolve.pyc:926)
> 2023-03-27 10:41:48,064 - StAI - DEBUG: Setting render settings: {'MarkIn': 0, 'MarkOut': 15000, 'CustomName': 'Timeline 1 1679906508', 'TargetDir': '/Users/nodal2catalina/Desktop/TRANSCRIPT COSQUER/untitled folder'} (mots_resolve.pyc:1056)
> 2023-03-27 10:41:48,065 - StAI - DEBUG: Adding render job to queue (mots_resolve.pyc:1059)
> 2023-03-27 10:41:48,231 - StAI - INFO: Starting render (mots_resolve.pyc:1085)
> 2023-03-27 10:42:26,528 - StAI - INFO: Config setting transcripts_skip_settings saved as "False"  (app.py:11497)
> 2023-03-27 10:42:26,528 - StAI - DEBUG: Loading config file /Users/nodal2catalina/StoryToolkitAI/config.json. (app.py:11553)
> 2023-03-27 10:42:26,528 - StAI - INFO: Updated config file /Users/nodal2catalina/StoryToolkitAI/config.json with transcripts_skip_settings data. (app.py:11523)
> 2023-03-27 10:42:26,529 - StAI - INFO: Config file /Users/nodal2catalina/StoryToolkitAI/config.json saved. (app.py:11540)
> 2023-03-27 10:42:26,672 - StAI - INFO: Config setting transcription_pre_detect_speech saved as "True"  (app.py:11497)
> 2023-03-27 10:42:26,672 - StAI - DEBUG: Loading config file /Users/nodal2catalina/StoryToolkitAI/config.json. (app.py:11553)
> 2023-03-27 10:42:26,672 - StAI - INFO: Updated config file /Users/nodal2catalina/StoryToolkitAI/config.json with transcription_pre_detect_speech data. (app.py:11523)
> 2023-03-27 10:42:26,673 - StAI - INFO: Config file /Users/nodal2catalina/StoryToolkitAI/config.json saved. (app.py:11540)
> 2023-03-27 10:42:26,673 - StAI - INFO: Config setting transcription_word_timestamps saved as "True"  (app.py:11497)
> 2023-03-27 10:42:26,674 - StAI - DEBUG: Loading config file /Users/nodal2catalina/StoryToolkitAI/config.json. (app.py:11553)
> 2023-03-27 10:42:26,674 - StAI - INFO: Updated config file /Users/nodal2catalina/StoryToolkitAI/config.json with transcription_word_timestamps data. (app.py:11523)
> 2023-03-27 10:42:26,674 - StAI - INFO: Config file /Users/nodal2catalina/StoryToolkitAI/config.json saved. (app.py:11540)
> 2023-03-27 10:43:18,391 - StAI - INFO: Starting to transcribe Timeline 1 (app.py:9325)
> 2023-03-27 10:43:18,391 - StAI - INFO: Using cpu for Torch / Whisper. (app.py:8737)
> 2023-03-27 10:43:18,406 - StAI - DEBUG: Closing window: ts-Timeline 1-1679906507 (app.py:5234)
> 2023-03-27 10:43:18,415 - StAI - INFO: Config setting whisper_model_downloaded_large-v2 saved as "False"  (app.py:11497)
> 2023-03-27 10:43:18,415 - StAI - DEBUG: Loading config file /Users/nodal2catalina/StoryToolkitAI/config.json. (app.py:11553)
> 2023-03-27 10:43:18,415 - StAI - INFO: Updated config file /Users/nodal2catalina/StoryToolkitAI/config.json with whisper_model_downloaded_large-v2 data. (app.py:11523)
> 2023-03-27 10:43:18,416 - StAI - INFO: Config file /Users/nodal2catalina/StoryToolkitAI/config.json saved. (app.py:11540)
> 2023-03-27 10:43:18,416 - StAI - WARNING: The whisper large-v2 model may need to be downloaded and could take a while depending on the Internet connection speed.  (app.py:9806)
> 2023-03-27 10:43:18,431 - StAI - INFO: Loading Whisper large-v2 model. (app.py:9816)
> 2023-03-27 10:47:09,984 - StAI - DEBUG: Loading config file /Users/nodal2catalina/StoryToolkitAI/config.json. (app.py:11553)
> 2023-03-27 10:47:09,985 - StAI - INFO: Updated config file /Users/nodal2catalina/StoryToolkitAI/config.json with whisper_model_downloaded_large-v2 data. (app.py:11523)
> 2023-03-27 10:47:09,985 - StAI - INFO: Config file /Users/nodal2catalina/StoryToolkitAI/config.json saved. (app.py:11540)
> 2023-03-27 10:47:09,986 - StAI - INFO: Selected Whisper model is multilingual. (app.py:9833)
> 2023-03-27 10:47:16,643 - StAI - INFO: Detecting speech intervals in the audio. (app.py:9872)
> 2023-03-27 10:47:16,648 - StAI - INFO: Pre-detecting speech intervals in the audio. (app.py:9877)
> 2023-03-27 10:47:16,780 - StAI - ERROR: Traceback (most recent call last):
>   File "/Applications/StoryToolkitAI.0.17.16.x86_64.app/Contents/Resources/app.py", line 9337, in transcribe_from_queue
>   File "/Applications/StoryToolkitAI.0.17.16.x86_64.app/Contents/Resources/app.py", line 9880, in whisper_transcribe
>   File "/Applications/StoryToolkitAI.0.17.16.x86_64.app/Contents/Resources/app.py", line 9431, in get_speech_intervals
>   File "/Applications/StoryToolkitAI.0.17.16.x86_64.app/Contents/Resources/lib/python3.9/torch/hub.py", line 555, in load
>   File "/Applications/StoryToolkitAI.0.17.16.x86_64.app/Contents/Resources/lib/python3.9/torch/hub.py", line 212, in _get_cache_or_reload
>   File "/Applications/StoryToolkitAI.0.17.16.x86_64.app/Contents/Resources/lib/python3.9/torch/hub.py", line 309, in _check_repo_is_trusted
> PermissionError: [Errno 13] Permission denied: '/Users/nodal2catalina/.cache/torch/hub/trusted_list'
>  (app.py:9342)
> 2023-03-27 10:47:16,786 - StAI - INFO: Transcription queue empty. Going to sleep. (app.py:9301)

**Comment by octimot** [comment]
This is probably because the certificates in the standalone app have been changed.

Try deleting the cache folder. 
Open `terminal`, and execute `rm -rf /Users/nodal2catalina/.cache/hub`

Let me know if this works!
Cheers

**Comment by Momomio** [comment]
And it works !

**Comment by octimot** [comment]
Great, thanks! I'll add this note to the release notes.

**Comment by Momomio** [comment]
Just to clarify, I had to delete the `torch` folder and not just the `hub` folder so `rm -rf /Users/nodal2catalina/.cache/torch`

**Comment by octimot** [comment]
Gotcha! Thanks
