### ISSUE TITLE
UserWarning: Failed to launch Triton kernels

### ISSUE THREAD

**Issue by psp631** [octimot/StoryToolkitAI#79]
C:\Portable\StoryToolkitAI\venv\lib\site-packages\whisper\timing.py:42: UserWarning: Failed to launch Triton kernels, likely due to missing CUDA toolkit; falling back to a slower median kernel implementation...
  warnings.warn(
C:\Portable\StoryToolkitAI\venv\lib\site-packages\whisper\timing.py:146: UserWarning: Failed to launch Triton kernels, likely due to missing CUDA toolkit; falling back to a slower DTW implementation...

**Comment by octimot** [comment]
Thanks for the feedback!

We've seen this happening on some machines... will try to figure out why, but it should not have any effect on the quality of the output. Also, the speed should be the same as in the last version.

Cheers!

**Comment by octimot** [comment]
It seems that Triton kernels are not available for Windows: see this: https://github.com/openai/whisper/discussions/1283

I'm closing this issues since the only way to fix this is to compile your own Triton kernels and I'm not sure you can do that on Windows.
