### ISSUE TITLE
Selecting "Translate Timeline to English" doesn't translate, just gives the foreign language transcript

### ISSUE THREAD

**Issue by Reelback96** [octimot/StoryToolkitAI#8]
I ran a 1 hour INTV through this using the "large" option. I set my language to Portuguese, and when it finished it presented me with a Portuguese transcript, rather than an English one.

Here's my Terminal information:

```
(venv) LibraryFilmsO26:~ LibraryFilmsO26$ python StoryToolkitAI/app.py 
Running StoryToolkit version 0.16.14
Using cpu for Torch / Whisper.
Unable to find module DaVinciResolveScript from $PYTHONPATH - trying default locations
Starting StoryToolkitAI GUI
Prompting user for render path.
Project settings directory /Users/LibraryFilmsO26/StoryToolkitAI/projects/ai test doesn't exist.
Creating project settings directory.
Updated project settings file /Users/LibraryFilmsO26/StoryToolkitAI/projects/ai test/project.json.
Saving into /Volumes/LF_SSD_03/AI TEST/KOXA and starting render.
Starting to transcribe GMAC3_20211130_NAZARE_Rodrigo Koxa_INTV
Using cpu for Torch / Whisper.
Currently transcribing: GMAC3_20211130_NAZARE_Rodrigo Koxa_INTV
Loading Whisper large model.
Selected Whisper model is multilingual.
Transcribing GMAC3_20211130_NAZARE_Rodrigo Koxa_INTV.
This may take a while.
/Users/LibraryFilmsO26/venv/lib/python3.9/site-packages/whisper/transcribe.py:78: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
Finished transcription for GMAC3_20211130_NAZARE_Rodrigo Koxa_INTV in 43952 seconds
Config setting transcripts_always_on_top saved as False 
Updated config file /Users/LibraryFilmsO26/StoryToolkitAI/config.json with transcripts_always_on_top data.

```
Thanks!

**Comment by Reelback96** [comment]
In the options window, I selected "Transcribe + Translate". I'm now going to run one with just "Translate" chosen, and with no source language specified.

**Comment by octimot** [comment]
This is intended, thanks for pointing it out! I will make it more obvious in the README.

A bit of baseline: Whisper is speech-to-text, which means that you always need to feed it audio in order to produce the transcriptions. Therefore, the transcribe+translate process should simply create two jobs in the queue: a transcription job and a translation job which run one after the other directly on the audio file. Unfortunately, this means that it will take 2x the time.

I'm looking for ways to see if this could be optimized somehow!

Side question: was the medium model giving you weird results? In our editing room, we only use the large model for complicated audio, but most times the medium model produces pretty ok results (even for Portugese)

**Comment by octimot** [comment]
BTW, if you don't select the language, Whisper basically decides what language it's looking at after the first 30 seconds of the audio. The auto-select takes a bit more time to process and, if you have other languages spoken at the beginning of the audio more than others, it might give you fake results.

**Comment by Reelback96** [comment]
Ahh, I understand. It's doing two jobs - transcribing the footage in the original language, and translating it into English.

I was just testing the large model to see if it was any better. We have some verite footage I'm going to try this on which might benefit from the large model later on. The medium or base model produced very good results earlier.

As an aside - it seems like the subs it produced for an hour-long interview were pretty accurate in substance, but fairly off in terms of timing. I'm wondering if this is because I didn't choose a language, and the first two minutes were english before the Portguese took over. I don't know why this would effect timing, but it may have?

**Comment by octimot** [comment]
Not selecting the language shouldn't affect the timing. Do you feel it's drifting (starts with a small offset and then becomes larger or larger), or is it randomly off? Do you have periods of silence in your footage? - that could be the culprit.

**Comment by Reelback96** [comment]
It seems fairly random, but sometimes it's on point. The subtitles are more often coming in early than late. I think it might be getting confused by:

1) quick exchanges between multiple people
2) moving from English to Portuguese and back

**Comment by octimot** [comment]
@Reelback96 Are you seeing this issue inside the transcription window or in the subtitles imported in Resolve? Also, what frame rate is the timeline?

Something similar happened to us on a transcript with people speaking in Spanish, although I noticed that the drift was only happening on the SRT files that we imported in Resolve, but clicking the phrases in the transcription window took the playhead on the right timecode.

Also, we were having this issue with a 23.976 fps timeline.

**Comment by Reelback96** [comment]
It seems like it messes up mainly when there's exchanges of languages other than the selected one, either alternating languages or just extended, quick dialogue in the other language. See below:

![image](https://user-images.githubusercontent.com/114952726/197885936-e304e1d8-9f09-4ff5-91cb-07680df3d7f1.png)

These exchanges are in English from an INTV mainly in Portuguese, and they don't really line up with the speakers.

**Comment by octimot** [comment]
Sure, but is it just the SRT or is it out of sync when you navigate in the the timeline from the transcription window too? Does it also place the markers at the wrong times on the timeline when you select with V / up/down and then press M?

Also what framerate is your timeline?
