### ISSUE TITLE
M1 Mac Standalone 0.17.16 Launch Issue (w possible fix)

### ISSUE THREAD

**Issue by mwarf** [octimot/StoryToolkitAI#80]
M1 MacBook Air user on Ventura 13.2.1

Launch Error with the standalone .app

Terminal gives me this error:

Applications/StoryToolkitAI.0.17.16.arm64.app/Contents/Resources/lib/python3.9/torchaudio/_internal/module_utils.py:99: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.

**Comment by octimot** [comment]
Thanks for the feedback!

Is this affecting any functionality?

**Comment by mwarf** [comment]
Yes, the app refuses to launch at all. I sidestepped it by pulling from git and running the terminal version instead. But I have friends that would benefit from the standalone version.

**Comment by octimot** [comment]
It's difficult to tell what is going on from a single line, and the soundfile package is not critical for the GUI launch.

Could you send me the entire error message?

Also, did others mention seeing a similar error or having problems launching - just asking because you mentioned your friends.

Cheers!

**Comment by mwarf** [comment]
I tried to reproduce the error, but it runs now (I had installed all the requirements from the command line version and rebooted).

**Comment by octimot** [comment]
Alright, thanks again for reporting.

I'll keep the issue open just in case somebody else notices this on the standalone version.

**Comment by Momomio** [comment]
Hello,

I also have a launch bug for the Standalone Version on a Mac Studio M1 Max Monterey :

"Launch error

Launch error
See the py2app website for debugging launch issues"

And the link given : https://py2app.readthedocs.io/en/latest/debugging.html

![Capture d’écran 2023-03-30 à 16 37 15](https://user-images.githubusercontent.com/15261647/228872962-db17b844-9a5d-41d6-ad56-ae4edd2b3c11.png)

And this is what I have when I launch with the terminal :

> /Applications/StoryToolkitAI.0.17.16.arm64.app/Contents/Resources/lib/python3.9/torchaudio/_internal/module_utils.py:99: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
> Traceback (most recent call last):
>   File "soundfile.pyc", line 164, in <module>
> OSError: cannot load library '/Applications/StoryToolkitAI.0.17.16.arm64.app/Contents/Resources/lib/python39.zip/_soundfile_data/libsndfile_arm64.dylib': dlopen(/Applications/StoryToolkitAI.0.17.16.arm64.app/Contents/Resources/lib/python39.zip/_soundfile_data/libsndfile_arm64.dylib, 0x0002): tried: '/Applications/StoryToolkitAI.0.17.16.arm64.app/Contents/Resources/lib/python39.zip/_soundfile_data/libsndfile_arm64.dylib' (no such file)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "soundfile.pyc", line 171, in <module>
> OSError: cannot load library '/Applications/StoryToolkitAI.0.17.16.arm64.app/Contents/Resources/../Frameworks/libsndfile.dylib': dlopen(/Applications/StoryToolkitAI.0.17.16.arm64.app/Contents/Resources/../Frameworks/libsndfile.dylib, 0x0002): Library not loaded: @rpath/libmpg123.0.dylib
>   Referenced from: /Applications/StoryToolkitAI.0.17.16.arm64.app/Contents/Frameworks/libsndfile.1.0.34.dylib
>   Reason: tried: '/Applications/StoryToolkitAI.0.17.16.arm64.app/Contents/Frameworks/libmpg123.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/Applications/StoryToolkitAI.0.17.16.arm64.app/Contents/Frameworks/libmpg123.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/libmpg123.0.dylib' (no such file)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Applications/StoryToolkitAI.0.17.16.arm64.app/Contents/Resources/__boot__.py", line 311, in <module>
>     _run()
>   File "/Applications/StoryToolkitAI.0.17.16.arm64.app/Contents/Resources/__boot__.py", line 174, in _run
>     exec(compile(source, path, "exec"), globals(), globals())
>   File "/Applications/StoryToolkitAI.0.17.16.arm64.app/Contents/Resources/app.py", line 29, in <module>
>     import soundfile
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "soundfile.pyc", line 190, in <module>
> OSError: cannot load library '/usr/local/lib/libsndfile.dylib': dlopen(/usr/local/lib/libsndfile.dylib, 0x0002): tried: '/usr/local/lib/libsndfile.dylib' (no such file)
> 2023-03-30 16:45:55.253 StoryToolkitAI.0.17.16.arm64[4078:37499] Launch error
> 2023-03-30 16:45:55.253 StoryToolkitAI.0.17.16.arm64[4078:37499] Launch error
> See the py2app website for debugging launch issues
>

**Comment by octimot** [comment]
@mwarf @Momomio 

It looks like it was a compilation error, when compiling the tool into the standalone version.

I've just uploaded a fixed release: [StoryToolkitAI.0.17.16.1.arm64.app.zip](https://github.com/octimot/StoryToolkitAI/releases/download/v0.17.16/StoryToolkitAI.0.17.16.1.arm64.app.zip)
(also available on the [releases page](https://github.com/octimot/StoryToolkitAI/releases))

Would you mind checking this on your machine and let us know if it works?

Cheers!

**Comment by Momomio** [comment]
Thank you for the rapid fix ! 
I will test it first thing monday morning when I'll go back to work !

**Comment by octimot** [comment]
@Momomio This is due to issue #82 which was just fixed in the non-standalone version. 

But I'll upload a new standalone release containing the bugfix as soon as we manage to compile it (latest next week!).

In the meantime, if you don't want to deal with the non-standalone installation, (via `git`), just create the missing directory - for eg.: '/Users/grandangle/StoryToolkitAI/projects/Untitled Project 2023-04-03_105708/'

Cheers

**Comment by Momomio** [comment]
@octimot I just tested the last standalone release and everything works !
