### ISSUE TITLE
Feature Request - Permanent Transcribe Audio Button 

### ISSUE THREAD

**Issue by GypsyAcidQueen** [octimot/StoryToolkitAI#81]
Hey team. 

Little feature request. I would love to have the transcribe audio button available even when Resolve is open. At the moment it disappears when connected to the Resolve API.

Best~

**Comment by octimot** [comment]
Just Shift Click on the Transcribe Timeline button and it will do just that.

This is buried deep in [FEATURES.md > Other shortcuts etc.](https://github.com/octimot/StoryToolkitAI/blob/main/FEATURES.md#transcription-window-shortcuts)

We will have to find a way to make these easier to see some day...

**Comment by octimot** [comment]
Also, you can then Shift select multiple audio files to add them all in the queue...
