### ISSUE TITLE
How to export SRT from standalone?

### ISSUE THREAD

**Issue by E5GEN2** [octimot/StoryToolkitAI#84]
Seems like there is no way to export SRT with timecodes if there is no resolve.
IS there any way to do it?

**Comment by octimot** [comment]
The SRT file is saved in the same folder as the original audio file.

We'll add a more obvious way of exporting soon!

**Comment by octimot** [comment]
This was resolved with version 0.18.1 via menu buttons: https://github.com/octimot/StoryToolkitAI/blob/main/CHANGELOG.md
