### ISSUE TITLE
A feature to eliminate gaps between subtitles in generated .srt files

### ISSUE THREAD

**Issue by Cywilek** [octimot/StoryToolkitAI#88]
I am missing a feature that would eliminate gaps between individual subtitles in the generated .srt file. For example, if the first subtitle ends at 00:00:10,000 and the next one begins at 00:00:12,500, the first subtitle should be extended until 00:00:12,500 to avoid a gap between the subtitles. Currently, I have to manually extend the subtitles in DaVinci Resolve, which is a huge waste of time.

Is there a function that allows for such .srt generation? If so, I would be grateful for its indication.

**Comment by octimot** [comment]
Hey there!

This was requested multiple times and now experimentally possible starting from version 0.17.19 - currently only available for [Patreon Frequent Users and Producers](https://www.patreon.com/StoryToolkitAI).

Cheers!

**Comment by Cywilek** [comment]
Thank you!
