### ISSUE TITLE
storytoolkit won't launch Mac M1

### ISSUE THREAD

**Issue by peregrineb** [octimot/StoryToolkitAI#91]
**Describe the bug**
I'm a filmmaker who'd like to try using Storytoolkit to make transcripts for a documentary's interviews. After I installed the latest release for M1 Macs, I got this:

“StoryToolkitAI.0.17.16.2.arm64” can’t be opened because Apple cannot check it for malicious software." and "contact developer"

**To Reproduce**
n/a

**Expected behavior**

**Log file**
I don't think this would exist since I haven't launched

**Screenshots**
If possible, add screenshots to help explain your problem.
![Screenshot 2023-04-07 at 11 12 57 AM](https://user-images.githubusercontent.com/130177448/230657362-01593fb6-f44b-4bc5-8766-68cd2b94fa1a.png)

**System (please complete the following information):**
 - OS: Ventura 13.2.1 (22D68) on an M1 Macbook Pro, 64 GB ram
 - Python versions installed N/a, I'm not a coder
 - StoryToolkitAI Version StoryToolkitAI.0.17.16.2.arm64

**Additional context**
please write me at pernbeckman@gmail.com if there's anything else I can tell you.
![Screenshot 2023-04-07 at 11 15 14 AM](https://user-images.githubusercontent.com/130177448/230657657-305d7e24-c048-4ce7-a7d0-5ecbeb6c9922.png)

**Comment by octimot** [comment]
Just right click and Open -> Open.

Please read instructions on [Release page](https://github.com/octimot/StoryToolkitAI/releases/latest) for details.
