### ISSUE TITLE
Question about language detection and subtitle format

### ISSUE THREAD

**Issue by Momomio** [octimot/StoryToolkitAI#93]
Hi,

First, I was wondering, on the language detection function, when you don't select a language when launching a transcription, the prompt show "INFO: Detecting language using up to the first 30 seconds." how exactly did that work ? 
Is It looking the first 30 seconds to determine the language until it no longer detect a speech ?
If it's the case, could it be possible to have an option to launch a new detection every time it finishes a sentence ? It could be useful to have a better transcription when launching on rushs with multilanguage speaks, even if it's take a much longueur time to transcript.

My second question is about the subtitle format created by StoryToolkiAi, for now it's .srt but do you intent to add other format like .stl or .txt ? For direct integration into Avid Media Composer, for exemple...

**Comment by octimot** [comment]
Hello!

> It could be useful to have a better transcription when launching on rushs with multilanguage speaks, even if it's take a much longueur time to transcript.

I presume this would take considerably more time per transcription... but it could be useful, I agree.
I'd love to hear what kind of stuff you work on usually that made you think of this, if you can share!

> My second question is about the subtitle format created by StoryToolkiAi, for now it's .srt but do you intent to add other format like .stl or .txt ? For direct integration into Avid Media Composer, for exemple...

Yes, definitely. We're also looking into ways to import `markers` and `timelines` into Avid MC and other NLE software too... 
Do you use MC more often than Resolve or others?


We're currently focused on integrating the Assistant / ChatGPT feature really well and working on some features suggested by some of our Patrons, but we'll explore these features as soon as we can squeeze them in the backlog.

Cheers!

**Comment by Momomio** [comment]
> I'd love to hear what kind of stuff you work on usually that made you think of this, if you can share!

Of course, we're mostly working on documentary. 
Sometimes they follow multicultural team who speak different language and for example, we're currently working on a little documentary series/show with episode in multiple different countries, so we have a lot of rushes with people speaking french (our native langage), english and the language of the country they're in and often when they speak, they switch language every two sentences... 

> Do you use MC more often than Resolve or others?

For the moment, yes.
Like I said we're mostly on documentary and they're always done on MC, for tv magazine we are, little by little, moving to Resolve but for the moment we have more stuff on MC than Resolve.
So when we use StoryToolkit it's more with the standalone version to generate a transcription from a MP4 or a WAV, and we put the generated .srt into [SubtitleEdit](https://www.nikse.dk/subtitleedit) to have a .stl readable by MC.

> We're currently focused on integrating the Assistant / ChatGPT feature really well and working on some features suggested by some of our Patrons, but we'll explore these features as soon as we can squeeze them in the backlog.

Thank you for that ! I'm looking forward to seeing the next updates !

**Comment by octimot** [comment]
Cool! Thanks for the feedback!

BTW, for multilingual rushes, I recommend using the re-transcribe feature. Just select all the segments that are in a different language and then press T. To move quickly with the selection, instead of using key V, try to select the first and the last segment and then press Shift+A, each text block at a time.

Hope this makes sense! Cheers!

**Comment by Momomio** [comment]
I admit that we don't always check the transcription with the transcription window because we have many clips put together and end up with a mp4 of several hours per camera card, we check once we're in MC. So come back to StoryToolkit and find the passage to re-transcribe can be tedious. 
But now that I think of it, is it possible to add, on the transcription window, on option to directly go on a certain timecode ? And maybe another option to see the TC at the beginning of each sentence, like when open the .srt file ? 

That way we can derush on MC and when we see section which need to be re-transcribe we can relaunch StoryToolkit and directly go to the section we want to re-transcribe

**Comment by Momomio** [comment]
Or, as I always check after proposing my idea, just open the transcription window, hit T and put the TC on Time Intervals... ^^

**Comment by octimot** [comment]
Regarding other subtitle formats, I just pushed an early non-standalone update for Patrons, which includes the ability to export to Avid DS directly from the tool - version 0.18.2.

About this:

> But now that I think of it, is it possible to add, on the transcription window, on option to directly go on a certain timecode ? And maybe another option to see the TC at the beginning of each sentence, like when open the .srt file ?

This sounds like a smart proposal though especially when you can use timecodes instead of seconds! We'll add it to the backlog.

Cheers!

**Comment by octimot** [comment]
Version 0.18.4 now has the Go To Timecode function - just press the `=` key in any transcription window and enter your timecode!

Cheers

**Comment by Momomio** [comment]
Well you're a true dream maker ^^

Thank you for all your awesome work !
