### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by mattiesongithub** [octimot/StoryToolkitAI#94]
I know a tiny bit of python, no clue what it means
![image](https://user-images.githubusercontent.com/127859729/232136651-e5ba6753-9a4c-49e3-82dd-c8ee35f760c4.png)

**Comment by octimot** [comment]
Please use the full issue template next time when you report something. It's hard to tell what is going on without more details about tool version, OS etc.

So, what is the version of the tool you're trying to start up?
What Python versions do you have installed on your machine?
Which version of Windows are you running?

Also, did you go through [all the installation steps](https://github.com/octimot/StoryToolkitAI/blob/main/INSTALLATION.md#windows)?

The error tells you that the tool did not find the module `requests`. This could mean a many things:
- you either haven't installed all the requirements [steps 7-9](https://github.com/octimot/StoryToolkitAI/blob/main/INSTALLATION.md#1-download-and-install-python) or
- you're py command is linked to another version of python which is not the one in your (venv) virtual environment - you could technically find that out by running `where py` or
- you're not using an official Python 3.9 installer as mentioned on [step 1](https://github.com/octimot/StoryToolkitAI/blob/main/INSTALLATION.md#1-download-and-install-python).
- etc.
