### ISSUE TITLE
Not compatible with Resolve 18.5 Beta?

### ISSUE THREAD

**Issue by yokhalel** [octimot/StoryToolkitAI#96]
Hey @octimot , 

StoryToolkitAI v0.17.16 doesn't work with the new Beta Update of Resolve. After Audio Rendering the tool gives this Error: 

"ERROR: Missing parameters to add file to transcription queue"

I uninstalled Resolve Beta and went back to the last stable Version 18.1.4, which worked perfect again. 

Thank you for the constant updates!

**Comment by octimot** [comment]
Thanks for reporting this!

We'll look into it as soon as we wrap up some projects here and get to install the new version of Resolve - it would be a disaster to break our editing room with the Beta! :-D

**Comment by SilentDude80** [comment]
I'm on v0.17.17 - no problems here with Resolve 18.5 Beta...

**Comment by ryzen88** [comment]
I have 0.18.1 story and run 18.5 without issues
